// Code generated by entc, DO NOT EDIT.

package slackappinstall

import (
	"fmt"
	"time"

	"github.com/10hourlabs/tentn/ent/schema/billing"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the slackappinstall type in the database.
	Label = "slack_app_install"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldTeamID holds the string denoting the team_id field in the database.
	FieldTeamID = "team_id"
	// FieldTeamName holds the string denoting the team_name field in the database.
	FieldTeamName = "team_name"
	// FieldAuthedUserID holds the string denoting the authed_user_id field in the database.
	FieldAuthedUserID = "authed_user_id"
	// FieldAuthedUserEmail holds the string denoting the authed_user_email field in the database.
	FieldAuthedUserEmail = "authed_user_email"
	// FieldAuthedUserTitle holds the string denoting the authed_user_title field in the database.
	FieldAuthedUserTitle = "authed_user_title"
	// FieldAuthedUserPhone holds the string denoting the authed_user_phone field in the database.
	FieldAuthedUserPhone = "authed_user_phone"
	// FieldAppID holds the string denoting the app_id field in the database.
	FieldAppID = "app_id"
	// FieldBotUserID holds the string denoting the bot_user_id field in the database.
	FieldBotUserID = "bot_user_id"
	// FieldAccessToken holds the string denoting the access_token field in the database.
	FieldAccessToken = "access_token"
	// FieldTokenType holds the string denoting the token_type field in the database.
	FieldTokenType = "token_type"
	// FieldScope holds the string denoting the scope field in the database.
	FieldScope = "scope"
	// FieldIsEnterpriseInstall holds the string denoting the is_enterprise_install field in the database.
	FieldIsEnterpriseInstall = "is_enterprise_install"
	// FieldPaymentPlan holds the string denoting the payment_plan field in the database.
	FieldPaymentPlan = "payment_plan"
	// FieldInstallCount holds the string denoting the install_count field in the database.
	FieldInstallCount = "install_count"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeSlackAppUsers holds the string denoting the slack_app_users edge name in mutations.
	EdgeSlackAppUsers = "slack_app_users"
	// Table holds the table name of the slackappinstall in the database.
	Table = "slack_app_installs"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "slack_app_installs"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// SlackAppUsersTable is the table that holds the slack_app_users relation/edge.
	SlackAppUsersTable = "slack_app_users"
	// SlackAppUsersInverseTable is the table name for the SlackAppUser entity.
	// It exists in this package in order to avoid circular dependency with the "slackappuser" package.
	SlackAppUsersInverseTable = "slack_app_users"
	// SlackAppUsersColumn is the table column denoting the slack_app_users relation/edge.
	SlackAppUsersColumn = "slack_app_install_id"
)

// Columns holds all SQL columns for slackappinstall fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldUserID,
	FieldTeamID,
	FieldTeamName,
	FieldAuthedUserID,
	FieldAuthedUserEmail,
	FieldAuthedUserTitle,
	FieldAuthedUserPhone,
	FieldAppID,
	FieldBotUserID,
	FieldAccessToken,
	FieldTokenType,
	FieldScope,
	FieldIsEnterpriseInstall,
	FieldPaymentPlan,
	FieldInstallCount,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultInstallCount holds the default value on creation for the "install_count" field.
	DefaultInstallCount int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

const DefaultPaymentPlan billing.PaymentPlan = "free"

// PaymentPlanValidator is a validator for the "payment_plan" field enum values. It is called by the builders before save.
func PaymentPlanValidator(pp billing.PaymentPlan) error {
	switch pp {
	case "free":
		return nil
	default:
		return fmt.Errorf("slackappinstall: invalid enum value for payment_plan field: %q", pp)
	}
}
