version: '3.8'

services:
  postgres:
    image: postgres:14
    networks:
      - tentn
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    networks:
      - tentn
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - .env

  metabase:
    depends_on:
      - postgres
    image: metabase/metabase
    networks:
      - tentn
    ports:
      - 5051:3000
    volumes:
      - metabase:/metabase-data/metabase.db
    env_file:
      - .env

  web:
    depends_on:
      - postgres
    build:
      context: .
      target: ${STAGE}
      args:
        - GITHUB_USER=GITHUB_USER
        - GITHUB_PERSONAL_TOKEN=GITHUB_PERSONAL_TOKEN
    networks:
      - tentn
    ports:
      - 5000:5000
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped

  webtest:
    tty: true
    stdin_open: true
    build:
      context: .
      target: test
    networks:
      - tentn
    environment:
      - ENV=test
    env_file:
      - .env

volumes:
  postgres:
  pgadmin:
  metabase:

networks:
  tentn:
    driver: bridge
