version: '3.8'

services:
  postgres:
    image: postgres:14
    networks:
      - tentn
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env
  
  redis:
    image: redis:7.0-alpine
    networks:
      - tentn
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    env_file:
      - .env

  pgadmin:
    depends_on:
      - postgres
    image: dpage/pgadmin4
    networks:
      - tentn
    ports:
      - 5050:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    env_file:
      - .env

  web:
    platform: linux/amd64
    depends_on:
      - postgres
    build:
      context: .
      target: ${STAGE}
      args:
        - GITHUB_USER=GITHUB_USER
        - GITHUB_PERSONAL_TOKEN=GITHUB_PERSONAL_TOKEN
    networks:
      - tentn
    ports:
      - 3000:5000
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped

  webtest:
    tty: true
    stdin_open: true
    build:
      context: .
      target: test
    networks:
      - tentn
    environment:
      - ENV=test
    env_file:
      - .env

volumes:
  postgres:
  redis:
  pgadmin:

networks:
  tentn:
    driver: bridge
