// Code generated by entc, DO NOT EDIT.

package jobapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/theterminalguy/tnet/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldID), id))
	})
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldID), id))
	})
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.In(s.C(FieldID), v...))
	})
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(ids) == 0 {
			s.Where(sql.False())
			return
		}
		v := make([]interface{}, len(ids))
		for i := range v {
			v[i] = ids[i]
		}
		s.Where(sql.NotIn(s.C(FieldID), v...))
	})
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldID), id))
	})
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldID), id))
	})
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldID), id))
	})
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldID), id))
	})
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// TalentID applies equality check predicate on the "talent_id" field. It's identical to TalentIDEQ.
func TalentID(v uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTalentID), v))
	})
}

// JobID applies equality check predicate on the "job_id" field. It's identical to JobIDEQ.
func JobID(v uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldJobID), v))
	})
}

// ReferralSource applies equality check predicate on the "referral_source" field. It's identical to ReferralSourceEQ.
func ReferralSource(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReferralSource), v))
	})
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNote), v))
	})
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldCreatedAt), v...))
	})
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldCreatedAt), v))
	})
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldCreatedAt), v))
	})
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldUpdatedAt), v...))
	})
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldUpdatedAt), v))
	})
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldUpdatedAt), v))
	})
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldDeletedAt), v...))
	})
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldDeletedAt), v))
	})
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldDeletedAt)))
	})
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldDeletedAt)))
	})
}

// TalentIDEQ applies the EQ predicate on the "talent_id" field.
func TalentIDEQ(v uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldTalentID), v))
	})
}

// TalentIDNEQ applies the NEQ predicate on the "talent_id" field.
func TalentIDNEQ(v uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldTalentID), v))
	})
}

// TalentIDIn applies the In predicate on the "talent_id" field.
func TalentIDIn(vs ...uuid.UUID) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldTalentID), v...))
	})
}

// TalentIDNotIn applies the NotIn predicate on the "talent_id" field.
func TalentIDNotIn(vs ...uuid.UUID) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldTalentID), v...))
	})
}

// TalentIDIsNil applies the IsNil predicate on the "talent_id" field.
func TalentIDIsNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldTalentID)))
	})
}

// TalentIDNotNil applies the NotNil predicate on the "talent_id" field.
func TalentIDNotNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldTalentID)))
	})
}

// JobIDEQ applies the EQ predicate on the "job_id" field.
func JobIDEQ(v uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldJobID), v))
	})
}

// JobIDNEQ applies the NEQ predicate on the "job_id" field.
func JobIDNEQ(v uuid.UUID) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldJobID), v))
	})
}

// JobIDIn applies the In predicate on the "job_id" field.
func JobIDIn(vs ...uuid.UUID) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldJobID), v...))
	})
}

// JobIDNotIn applies the NotIn predicate on the "job_id" field.
func JobIDNotIn(vs ...uuid.UUID) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldJobID), v...))
	})
}

// JobIDIsNil applies the IsNil predicate on the "job_id" field.
func JobIDIsNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldJobID)))
	})
}

// JobIDNotNil applies the NotNil predicate on the "job_id" field.
func JobIDNotNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldJobID)))
	})
}

// ReferralSourceEQ applies the EQ predicate on the "referral_source" field.
func ReferralSourceEQ(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceNEQ applies the NEQ predicate on the "referral_source" field.
func ReferralSourceNEQ(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceIn applies the In predicate on the "referral_source" field.
func ReferralSourceIn(vs ...string) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldReferralSource), v...))
	})
}

// ReferralSourceNotIn applies the NotIn predicate on the "referral_source" field.
func ReferralSourceNotIn(vs ...string) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldReferralSource), v...))
	})
}

// ReferralSourceGT applies the GT predicate on the "referral_source" field.
func ReferralSourceGT(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceGTE applies the GTE predicate on the "referral_source" field.
func ReferralSourceGTE(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceLT applies the LT predicate on the "referral_source" field.
func ReferralSourceLT(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceLTE applies the LTE predicate on the "referral_source" field.
func ReferralSourceLTE(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceContains applies the Contains predicate on the "referral_source" field.
func ReferralSourceContains(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceHasPrefix applies the HasPrefix predicate on the "referral_source" field.
func ReferralSourceHasPrefix(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceHasSuffix applies the HasSuffix predicate on the "referral_source" field.
func ReferralSourceHasSuffix(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceEqualFold applies the EqualFold predicate on the "referral_source" field.
func ReferralSourceEqualFold(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldReferralSource), v))
	})
}

// ReferralSourceContainsFold applies the ContainsFold predicate on the "referral_source" field.
func ReferralSourceContainsFold(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldReferralSource), v))
	})
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldStatus), v))
	})
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldStatus), v))
	})
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldStatus), v...))
	})
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldStatus), v...))
	})
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EQ(s.C(FieldNote), v))
	})
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NEQ(s.C(FieldNote), v))
	})
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.In(s.C(FieldNote), v...))
	})
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.JobApplication {
	v := make([]interface{}, len(vs))
	for i := range v {
		v[i] = vs[i]
	}
	return predicate.JobApplication(func(s *sql.Selector) {
		// if not arguments were provided, append the FALSE constants,
		// since we can't apply "IN ()". This will make this predicate falsy.
		if len(v) == 0 {
			s.Where(sql.False())
			return
		}
		s.Where(sql.NotIn(s.C(FieldNote), v...))
	})
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GT(s.C(FieldNote), v))
	})
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.GTE(s.C(FieldNote), v))
	})
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LT(s.C(FieldNote), v))
	})
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.LTE(s.C(FieldNote), v))
	})
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.Contains(s.C(FieldNote), v))
	})
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.HasPrefix(s.C(FieldNote), v))
	})
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.HasSuffix(s.C(FieldNote), v))
	})
}

// NoteIsNil applies the IsNil predicate on the "note" field.
func NoteIsNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.IsNull(s.C(FieldNote)))
	})
}

// NoteNotNil applies the NotNil predicate on the "note" field.
func NoteNotNil() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.NotNull(s.C(FieldNote)))
	})
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.EqualFold(s.C(FieldNote), v))
	})
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s.Where(sql.ContainsFold(s.C(FieldNote), v))
	})
}

// HasTalent applies the HasEdge predicate on the "talent" edge.
func HasTalent() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TalentTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TalentTable, TalentColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTalentWith applies the HasEdge predicate on the "talent" edge with a given conditions (other predicates).
func HasTalentWith(preds ...predicate.Talent) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(TalentInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, TalentTable, TalentColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasJob applies the HasEdge predicate on the "job" edge.
func HasJob() predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(JobTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobTable, JobColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasJobWith applies the HasEdge predicate on the "job" edge with a given conditions (other predicates).
func HasJobWith(preds ...predicate.Job) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.To(JobInverseTable, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, JobTable, JobColumn),
		)
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.JobApplication) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.JobApplication) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.JobApplication) predicate.JobApplication {
	return predicate.JobApplication(func(s *sql.Selector) {
		p(s.Not())
	})
}
