// Code generated by entc, DO NOT EDIT.

package workexperience

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the workexperience type in the database.
	Label = "work_experience"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldTalentID holds the string denoting the talent_id field in the database.
	FieldTalentID = "talent_id"
	// FieldCompanyName holds the string denoting the company_name field in the database.
	FieldCompanyName = "company_name"
	// FieldLocation holds the string denoting the location field in the database.
	FieldLocation = "location"
	// FieldJobTitle holds the string denoting the job_title field in the database.
	FieldJobTitle = "job_title"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStartDate holds the string denoting the start_date field in the database.
	FieldStartDate = "start_date"
	// FieldEndDate holds the string denoting the end_date field in the database.
	FieldEndDate = "end_date"
	// FieldPrimaryTechnologies holds the string denoting the primary_technologies field in the database.
	FieldPrimaryTechnologies = "primary_technologies"
	// EdgeTalent holds the string denoting the talent edge name in mutations.
	EdgeTalent = "talent"
	// Table holds the table name of the workexperience in the database.
	Table = "work_experiences"
	// TalentTable is the table that holds the talent relation/edge.
	TalentTable = "work_experiences"
	// TalentInverseTable is the table name for the Talent entity.
	// It exists in this package in order to avoid circular dependency with the "talent" package.
	TalentInverseTable = "talents"
	// TalentColumn is the table column denoting the talent relation/edge.
	TalentColumn = "talent_id"
)

// Columns holds all SQL columns for workexperience fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldTalentID,
	FieldCompanyName,
	FieldLocation,
	FieldJobTitle,
	FieldDescription,
	FieldStartDate,
	FieldEndDate,
	FieldPrimaryTechnologies,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
