// Code generated by entc, DO NOT EDIT.

package portfoliolink

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the portfoliolink type in the database.
	Label = "portfolio_link"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldURL holds the string denoting the url field in the database.
	FieldURL = "url"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldApplicantID holds the string denoting the applicant_id field in the database.
	FieldApplicantID = "applicant_id"
	// EdgeApplicant holds the string denoting the applicant edge name in mutations.
	EdgeApplicant = "applicant"
	// Table holds the table name of the portfoliolink in the database.
	Table = "portfolio_links"
	// ApplicantTable is the table that holds the applicant relation/edge.
	ApplicantTable = "portfolio_links"
	// ApplicantInverseTable is the table name for the Applicant entity.
	// It exists in this package in order to avoid circular dependency with the "applicant" package.
	ApplicantInverseTable = "applicants"
	// ApplicantColumn is the table column denoting the applicant relation/edge.
	ApplicantColumn = "applicant_id"
)

// Columns holds all SQL columns for portfoliolink fields.
var Columns = []string{
	FieldID,
	FieldUUID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldURL,
	FieldName,
	FieldApplicantID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultUUID holds the default value on creation for the "uuid" field.
	DefaultUUID func() uuid.UUID
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt func() time.Time
	// URLValidator is a validator for the "url" field. It is called by the builders before save.
	URLValidator func(string) error
)
