// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/emergencycontact"
	"github.com/10hourlabs/tentn/ent/predicate"
)

// EmergencyContactDelete is the builder for deleting a EmergencyContact entity.
type EmergencyContactDelete struct {
	config
	hooks    []Hook
	mutation *EmergencyContactMutation
}

// Where appends a list predicates to the EmergencyContactDelete builder.
func (ecd *EmergencyContactDelete) Where(ps ...predicate.EmergencyContact) *EmergencyContactDelete {
	ecd.mutation.Where(ps...)
	return ecd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ecd *EmergencyContactDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ecd.hooks) == 0 {
		affected, err = ecd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EmergencyContactMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ecd.mutation = mutation
			affected, err = ecd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ecd.hooks) - 1; i >= 0; i-- {
			if ecd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ecd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ecd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecd *EmergencyContactDelete) ExecX(ctx context.Context) int {
	n, err := ecd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ecd *EmergencyContactDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: emergencycontact.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: emergencycontact.FieldID,
			},
		},
	}
	if ps := ecd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ecd.driver, _spec)
}

// EmergencyContactDeleteOne is the builder for deleting a single EmergencyContact entity.
type EmergencyContactDeleteOne struct {
	ecd *EmergencyContactDelete
}

// Exec executes the deletion query.
func (ecdo *EmergencyContactDeleteOne) Exec(ctx context.Context) error {
	n, err := ecdo.ecd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{emergencycontact.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ecdo *EmergencyContactDeleteOne) ExecX(ctx context.Context) {
	ecdo.ecd.ExecX(ctx)
}
