// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/fileupload"
	"github.com/10hourlabs/tentn/ent/predicate"
	"github.com/10hourlabs/tentn/ent/user"
	"github.com/google/uuid"
)

// FileUploadQuery is the builder for querying FileUpload entities.
type FileUploadQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.FileUpload
	// eager-loading edges.
	withUser *UserQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the FileUploadQuery builder.
func (fuq *FileUploadQuery) Where(ps ...predicate.FileUpload) *FileUploadQuery {
	fuq.predicates = append(fuq.predicates, ps...)
	return fuq
}

// Limit adds a limit step to the query.
func (fuq *FileUploadQuery) Limit(limit int) *FileUploadQuery {
	fuq.limit = &limit
	return fuq
}

// Offset adds an offset step to the query.
func (fuq *FileUploadQuery) Offset(offset int) *FileUploadQuery {
	fuq.offset = &offset
	return fuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (fuq *FileUploadQuery) Unique(unique bool) *FileUploadQuery {
	fuq.unique = &unique
	return fuq
}

// Order adds an order step to the query.
func (fuq *FileUploadQuery) Order(o ...OrderFunc) *FileUploadQuery {
	fuq.order = append(fuq.order, o...)
	return fuq
}

// QueryUser chains the current query on the "user" edge.
func (fuq *FileUploadQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: fuq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := fuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := fuq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(fileupload.Table, fileupload.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, fileupload.UserTable, fileupload.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(fuq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first FileUpload entity from the query.
// Returns a *NotFoundError when no FileUpload was found.
func (fuq *FileUploadQuery) First(ctx context.Context) (*FileUpload, error) {
	nodes, err := fuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{fileupload.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (fuq *FileUploadQuery) FirstX(ctx context.Context) *FileUpload {
	node, err := fuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first FileUpload ID from the query.
// Returns a *NotFoundError when no FileUpload ID was found.
func (fuq *FileUploadQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{fileupload.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (fuq *FileUploadQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := fuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single FileUpload entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one FileUpload entity is found.
// Returns a *NotFoundError when no FileUpload entities are found.
func (fuq *FileUploadQuery) Only(ctx context.Context) (*FileUpload, error) {
	nodes, err := fuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{fileupload.Label}
	default:
		return nil, &NotSingularError{fileupload.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (fuq *FileUploadQuery) OnlyX(ctx context.Context) *FileUpload {
	node, err := fuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only FileUpload ID in the query.
// Returns a *NotSingularError when more than one FileUpload ID is found.
// Returns a *NotFoundError when no entities are found.
func (fuq *FileUploadQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = fuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = &NotSingularError{fileupload.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (fuq *FileUploadQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := fuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of FileUploads.
func (fuq *FileUploadQuery) All(ctx context.Context) ([]*FileUpload, error) {
	if err := fuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return fuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (fuq *FileUploadQuery) AllX(ctx context.Context) []*FileUpload {
	nodes, err := fuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of FileUpload IDs.
func (fuq *FileUploadQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := fuq.Select(fileupload.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (fuq *FileUploadQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := fuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (fuq *FileUploadQuery) Count(ctx context.Context) (int, error) {
	if err := fuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return fuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (fuq *FileUploadQuery) CountX(ctx context.Context) int {
	count, err := fuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (fuq *FileUploadQuery) Exist(ctx context.Context) (bool, error) {
	if err := fuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return fuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (fuq *FileUploadQuery) ExistX(ctx context.Context) bool {
	exist, err := fuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the FileUploadQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (fuq *FileUploadQuery) Clone() *FileUploadQuery {
	if fuq == nil {
		return nil
	}
	return &FileUploadQuery{
		config:     fuq.config,
		limit:      fuq.limit,
		offset:     fuq.offset,
		order:      append([]OrderFunc{}, fuq.order...),
		predicates: append([]predicate.FileUpload{}, fuq.predicates...),
		withUser:   fuq.withUser.Clone(),
		// clone intermediate query.
		sql:    fuq.sql.Clone(),
		path:   fuq.path,
		unique: fuq.unique,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (fuq *FileUploadQuery) WithUser(opts ...func(*UserQuery)) *FileUploadQuery {
	query := &UserQuery{config: fuq.config}
	for _, opt := range opts {
		opt(query)
	}
	fuq.withUser = query
	return fuq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.FileUpload.Query().
//		GroupBy(fileupload.FieldCreatedAt).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (fuq *FileUploadQuery) GroupBy(field string, fields ...string) *FileUploadGroupBy {
	group := &FileUploadGroupBy{config: fuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := fuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return fuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.FileUpload.Query().
//		Select(fileupload.FieldCreatedAt).
//		Scan(ctx, &v)
//
func (fuq *FileUploadQuery) Select(fields ...string) *FileUploadSelect {
	fuq.fields = append(fuq.fields, fields...)
	return &FileUploadSelect{FileUploadQuery: fuq}
}

func (fuq *FileUploadQuery) prepareQuery(ctx context.Context) error {
	for _, f := range fuq.fields {
		if !fileupload.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if fuq.path != nil {
		prev, err := fuq.path(ctx)
		if err != nil {
			return err
		}
		fuq.sql = prev
	}
	return nil
}

func (fuq *FileUploadQuery) sqlAll(ctx context.Context) ([]*FileUpload, error) {
	var (
		nodes       = []*FileUpload{}
		_spec       = fuq.querySpec()
		loadedTypes = [1]bool{
			fuq.withUser != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &FileUpload{config: fuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, fuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := fuq.withUser; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*FileUpload)
		for i := range nodes {
			fk := nodes[i].UserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	return nodes, nil
}

func (fuq *FileUploadQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := fuq.querySpec()
	_spec.Node.Columns = fuq.fields
	if len(fuq.fields) > 0 {
		_spec.Unique = fuq.unique != nil && *fuq.unique
	}
	return sqlgraph.CountNodes(ctx, fuq.driver, _spec)
}

func (fuq *FileUploadQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := fuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (fuq *FileUploadQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   fileupload.Table,
			Columns: fileupload.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: fileupload.FieldID,
			},
		},
		From:   fuq.sql,
		Unique: true,
	}
	if unique := fuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := fuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, fileupload.FieldID)
		for i := range fields {
			if fields[i] != fileupload.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := fuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := fuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := fuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := fuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (fuq *FileUploadQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(fuq.driver.Dialect())
	t1 := builder.Table(fileupload.Table)
	columns := fuq.fields
	if len(columns) == 0 {
		columns = fileupload.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if fuq.sql != nil {
		selector = fuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if fuq.unique != nil && *fuq.unique {
		selector.Distinct()
	}
	for _, p := range fuq.predicates {
		p(selector)
	}
	for _, p := range fuq.order {
		p(selector)
	}
	if offset := fuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := fuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// FileUploadGroupBy is the group-by builder for FileUpload entities.
type FileUploadGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (fugb *FileUploadGroupBy) Aggregate(fns ...AggregateFunc) *FileUploadGroupBy {
	fugb.fns = append(fugb.fns, fns...)
	return fugb
}

// Scan applies the group-by query and scans the result into the given value.
func (fugb *FileUploadGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := fugb.path(ctx)
	if err != nil {
		return err
	}
	fugb.sql = query
	return fugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fugb *FileUploadGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := fugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(fugb.fields) > 1 {
		return nil, errors.New("ent: FileUploadGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := fugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fugb *FileUploadGroupBy) StringsX(ctx context.Context) []string {
	v, err := fugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fugb *FileUploadGroupBy) StringX(ctx context.Context) string {
	v, err := fugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(fugb.fields) > 1 {
		return nil, errors.New("ent: FileUploadGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := fugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fugb *FileUploadGroupBy) IntsX(ctx context.Context) []int {
	v, err := fugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fugb *FileUploadGroupBy) IntX(ctx context.Context) int {
	v, err := fugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(fugb.fields) > 1 {
		return nil, errors.New("ent: FileUploadGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := fugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fugb *FileUploadGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := fugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fugb *FileUploadGroupBy) Float64X(ctx context.Context) float64 {
	v, err := fugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(fugb.fields) > 1 {
		return nil, errors.New("ent: FileUploadGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := fugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fugb *FileUploadGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := fugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (fugb *FileUploadGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fugb *FileUploadGroupBy) BoolX(ctx context.Context) bool {
	v, err := fugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fugb *FileUploadGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range fugb.fields {
		if !fileupload.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := fugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := fugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (fugb *FileUploadGroupBy) sqlQuery() *sql.Selector {
	selector := fugb.sql.Select()
	aggregation := make([]string, 0, len(fugb.fns))
	for _, fn := range fugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(fugb.fields)+len(fugb.fns))
		for _, f := range fugb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(fugb.fields...)...)
}

// FileUploadSelect is the builder for selecting fields of FileUpload entities.
type FileUploadSelect struct {
	*FileUploadQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (fus *FileUploadSelect) Scan(ctx context.Context, v interface{}) error {
	if err := fus.prepareQuery(ctx); err != nil {
		return err
	}
	fus.sql = fus.FileUploadQuery.sqlQuery(ctx)
	return fus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (fus *FileUploadSelect) ScanX(ctx context.Context, v interface{}) {
	if err := fus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) Strings(ctx context.Context) ([]string, error) {
	if len(fus.fields) > 1 {
		return nil, errors.New("ent: FileUploadSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := fus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (fus *FileUploadSelect) StringsX(ctx context.Context) []string {
	v, err := fus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = fus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (fus *FileUploadSelect) StringX(ctx context.Context) string {
	v, err := fus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) Ints(ctx context.Context) ([]int, error) {
	if len(fus.fields) > 1 {
		return nil, errors.New("ent: FileUploadSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := fus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (fus *FileUploadSelect) IntsX(ctx context.Context) []int {
	v, err := fus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = fus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (fus *FileUploadSelect) IntX(ctx context.Context) int {
	v, err := fus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(fus.fields) > 1 {
		return nil, errors.New("ent: FileUploadSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := fus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (fus *FileUploadSelect) Float64sX(ctx context.Context) []float64 {
	v, err := fus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = fus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (fus *FileUploadSelect) Float64X(ctx context.Context) float64 {
	v, err := fus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(fus.fields) > 1 {
		return nil, errors.New("ent: FileUploadSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := fus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (fus *FileUploadSelect) BoolsX(ctx context.Context) []bool {
	v, err := fus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (fus *FileUploadSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = fus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{fileupload.Label}
	default:
		err = fmt.Errorf("ent: FileUploadSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (fus *FileUploadSelect) BoolX(ctx context.Context) bool {
	v, err := fus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (fus *FileUploadSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := fus.sql.Query()
	if err := fus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
