// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/internaltask"
	"github.com/10hourlabs/tentn/ent/predicate"
)

// InternalTaskDelete is the builder for deleting a InternalTask entity.
type InternalTaskDelete struct {
	config
	hooks    []Hook
	mutation *InternalTaskMutation
}

// Where appends a list predicates to the InternalTaskDelete builder.
func (itd *InternalTaskDelete) Where(ps ...predicate.InternalTask) *InternalTaskDelete {
	itd.mutation.Where(ps...)
	return itd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (itd *InternalTaskDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(itd.hooks) == 0 {
		affected, err = itd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*InternalTaskMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			itd.mutation = mutation
			affected, err = itd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(itd.hooks) - 1; i >= 0; i-- {
			if itd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = itd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, itd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (itd *InternalTaskDelete) ExecX(ctx context.Context) int {
	n, err := itd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (itd *InternalTaskDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: internaltask.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: internaltask.FieldID,
			},
		},
	}
	if ps := itd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, itd.driver, _spec)
}

// InternalTaskDeleteOne is the builder for deleting a single InternalTask entity.
type InternalTaskDeleteOne struct {
	itd *InternalTaskDelete
}

// Exec executes the deletion query.
func (itdo *InternalTaskDeleteOne) Exec(ctx context.Context) error {
	n, err := itdo.itd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{internaltask.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (itdo *InternalTaskDeleteOne) ExecX(ctx context.Context) {
	itdo.itd.ExecX(ctx)
}
