// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/10hourlabs/tentn/ent/jobcollection"
	"github.com/10hourlabs/tentn/ent/user"
	"github.com/google/uuid"
)

// JobCollection is the model entity for the JobCollection schema.
type JobCollection struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at"`
	// RecruiterID holds the value of the "recruiter_id" field.
	RecruiterID uuid.UUID `json:"-"`
	// Status holds the value of the "status" field.
	Status jobcollection.Status `json:"status,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JobCollectionQuery when eager-loading is set.
	Edges JobCollectionEdges `json:"edges"`
}

// JobCollectionEdges holds the relations/edges for other nodes in the graph.
type JobCollectionEdges struct {
	// Users holds the value of the users edge.
	Users *User `json:"users,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UsersOrErr returns the Users value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JobCollectionEdges) UsersOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Users == nil {
			// The edge users was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Users, nil
	}
	return nil, &NotLoadedError{edge: "users"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobCollection) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobcollection.FieldStatus, jobcollection.FieldTitle:
			values[i] = new(sql.NullString)
		case jobcollection.FieldCreatedAt, jobcollection.FieldUpdatedAt, jobcollection.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		case jobcollection.FieldID, jobcollection.FieldRecruiterID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type JobCollection", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobCollection fields.
func (jc *JobCollection) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobcollection.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				jc.ID = *value
			}
		case jobcollection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				jc.CreatedAt = value.Time
			}
		case jobcollection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				jc.UpdatedAt = value.Time
			}
		case jobcollection.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				jc.DeletedAt = new(time.Time)
				*jc.DeletedAt = value.Time
			}
		case jobcollection.FieldRecruiterID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field recruiter_id", values[i])
			} else if value != nil {
				jc.RecruiterID = *value
			}
		case jobcollection.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				jc.Status = jobcollection.Status(value.String)
			}
		case jobcollection.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				jc.Title = value.String
			}
		}
	}
	return nil
}

// QueryUsers queries the "users" edge of the JobCollection entity.
func (jc *JobCollection) QueryUsers() *UserQuery {
	return (&JobCollectionClient{config: jc.config}).QueryUsers(jc)
}

// Update returns a builder for updating this JobCollection.
// Note that you need to call JobCollection.Unwrap() before calling this method if this JobCollection
// was returned from a transaction, and the transaction was committed or rolled back.
func (jc *JobCollection) Update() *JobCollectionUpdateOne {
	return (&JobCollectionClient{config: jc.config}).UpdateOne(jc)
}

// Unwrap unwraps the JobCollection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (jc *JobCollection) Unwrap() *JobCollection {
	tx, ok := jc.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobCollection is not a transactional entity")
	}
	jc.config.driver = tx.drv
	return jc
}

// String implements the fmt.Stringer.
func (jc *JobCollection) String() string {
	var builder strings.Builder
	builder.WriteString("JobCollection(")
	builder.WriteString(fmt.Sprintf("id=%v", jc.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(jc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(jc.UpdatedAt.Format(time.ANSIC))
	if v := jc.DeletedAt; v != nil {
		builder.WriteString(", deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", recruiter_id=")
	builder.WriteString(fmt.Sprintf("%v", jc.RecruiterID))
	builder.WriteString(", status=")
	builder.WriteString(fmt.Sprintf("%v", jc.Status))
	builder.WriteString(", title=")
	builder.WriteString(jc.Title)
	builder.WriteByte(')')
	return builder.String()
}

// JobCollections is a parsable slice of JobCollection.
type JobCollections []*JobCollection

func (jc JobCollections) config(cfg config) {
	for _i := range jc {
		jc[_i].config = cfg
	}
}
