// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/job"
	"github.com/10hourlabs/tentn/ent/jobtalent"
	"github.com/10hourlabs/tentn/ent/predicate"
	"github.com/10hourlabs/tentn/ent/talent"
)

// JobTalentQuery is the builder for querying JobTalent entities.
type JobTalentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.JobTalent
	// eager-loading edges.
	withTalent *TalentQuery
	withJob    *JobQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the JobTalentQuery builder.
func (jtq *JobTalentQuery) Where(ps ...predicate.JobTalent) *JobTalentQuery {
	jtq.predicates = append(jtq.predicates, ps...)
	return jtq
}

// Limit adds a limit step to the query.
func (jtq *JobTalentQuery) Limit(limit int) *JobTalentQuery {
	jtq.limit = &limit
	return jtq
}

// Offset adds an offset step to the query.
func (jtq *JobTalentQuery) Offset(offset int) *JobTalentQuery {
	jtq.offset = &offset
	return jtq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (jtq *JobTalentQuery) Unique(unique bool) *JobTalentQuery {
	jtq.unique = &unique
	return jtq
}

// Order adds an order step to the query.
func (jtq *JobTalentQuery) Order(o ...OrderFunc) *JobTalentQuery {
	jtq.order = append(jtq.order, o...)
	return jtq
}

// QueryTalent chains the current query on the "talent" edge.
func (jtq *JobTalentQuery) QueryTalent() *TalentQuery {
	query := &TalentQuery{config: jtq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobtalent.Table, jobtalent.FieldID, selector),
			sqlgraph.To(talent.Table, talent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobtalent.TalentTable, jobtalent.TalentColumn),
		)
		fromU = sqlgraph.SetNeighbors(jtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJob chains the current query on the "job" edge.
func (jtq *JobTalentQuery) QueryJob() *JobQuery {
	query := &JobQuery{config: jtq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := jtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := jtq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(jobtalent.Table, jobtalent.FieldID, selector),
			sqlgraph.To(job.Table, job.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, jobtalent.JobTable, jobtalent.JobColumn),
		)
		fromU = sqlgraph.SetNeighbors(jtq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first JobTalent entity from the query.
// Returns a *NotFoundError when no JobTalent was found.
func (jtq *JobTalentQuery) First(ctx context.Context) (*JobTalent, error) {
	nodes, err := jtq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{jobtalent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (jtq *JobTalentQuery) FirstX(ctx context.Context) *JobTalent {
	node, err := jtq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first JobTalent ID from the query.
// Returns a *NotFoundError when no JobTalent ID was found.
func (jtq *JobTalentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jtq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{jobtalent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (jtq *JobTalentQuery) FirstIDX(ctx context.Context) int {
	id, err := jtq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single JobTalent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one JobTalent entity is not found.
// Returns a *NotFoundError when no JobTalent entities are found.
func (jtq *JobTalentQuery) Only(ctx context.Context) (*JobTalent, error) {
	nodes, err := jtq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{jobtalent.Label}
	default:
		return nil, &NotSingularError{jobtalent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (jtq *JobTalentQuery) OnlyX(ctx context.Context) *JobTalent {
	node, err := jtq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only JobTalent ID in the query.
// Returns a *NotSingularError when exactly one JobTalent ID is not found.
// Returns a *NotFoundError when no entities are found.
func (jtq *JobTalentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = jtq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = &NotSingularError{jobtalent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (jtq *JobTalentQuery) OnlyIDX(ctx context.Context) int {
	id, err := jtq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of JobTalents.
func (jtq *JobTalentQuery) All(ctx context.Context) ([]*JobTalent, error) {
	if err := jtq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return jtq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (jtq *JobTalentQuery) AllX(ctx context.Context) []*JobTalent {
	nodes, err := jtq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of JobTalent IDs.
func (jtq *JobTalentQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := jtq.Select(jobtalent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (jtq *JobTalentQuery) IDsX(ctx context.Context) []int {
	ids, err := jtq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (jtq *JobTalentQuery) Count(ctx context.Context) (int, error) {
	if err := jtq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return jtq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (jtq *JobTalentQuery) CountX(ctx context.Context) int {
	count, err := jtq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (jtq *JobTalentQuery) Exist(ctx context.Context) (bool, error) {
	if err := jtq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return jtq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (jtq *JobTalentQuery) ExistX(ctx context.Context) bool {
	exist, err := jtq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the JobTalentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (jtq *JobTalentQuery) Clone() *JobTalentQuery {
	if jtq == nil {
		return nil
	}
	return &JobTalentQuery{
		config:     jtq.config,
		limit:      jtq.limit,
		offset:     jtq.offset,
		order:      append([]OrderFunc{}, jtq.order...),
		predicates: append([]predicate.JobTalent{}, jtq.predicates...),
		withTalent: jtq.withTalent.Clone(),
		withJob:    jtq.withJob.Clone(),
		// clone intermediate query.
		sql:  jtq.sql.Clone(),
		path: jtq.path,
	}
}

// WithTalent tells the query-builder to eager-load the nodes that are connected to
// the "talent" edge. The optional arguments are used to configure the query builder of the edge.
func (jtq *JobTalentQuery) WithTalent(opts ...func(*TalentQuery)) *JobTalentQuery {
	query := &TalentQuery{config: jtq.config}
	for _, opt := range opts {
		opt(query)
	}
	jtq.withTalent = query
	return jtq
}

// WithJob tells the query-builder to eager-load the nodes that are connected to
// the "job" edge. The optional arguments are used to configure the query builder of the edge.
func (jtq *JobTalentQuery) WithJob(opts ...func(*JobQuery)) *JobTalentQuery {
	query := &JobQuery{config: jtq.config}
	for _, opt := range opts {
		opt(query)
	}
	jtq.withJob = query
	return jtq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.JobTalent.Query().
//		GroupBy(jobtalent.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (jtq *JobTalentQuery) GroupBy(field string, fields ...string) *JobTalentGroupBy {
	group := &JobTalentGroupBy{config: jtq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := jtq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return jtq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.JobTalent.Query().
//		Select(jobtalent.FieldUUID).
//		Scan(ctx, &v)
//
func (jtq *JobTalentQuery) Select(fields ...string) *JobTalentSelect {
	jtq.fields = append(jtq.fields, fields...)
	return &JobTalentSelect{JobTalentQuery: jtq}
}

func (jtq *JobTalentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range jtq.fields {
		if !jobtalent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if jtq.path != nil {
		prev, err := jtq.path(ctx)
		if err != nil {
			return err
		}
		jtq.sql = prev
	}
	return nil
}

func (jtq *JobTalentQuery) sqlAll(ctx context.Context) ([]*JobTalent, error) {
	var (
		nodes       = []*JobTalent{}
		_spec       = jtq.querySpec()
		loadedTypes = [2]bool{
			jtq.withTalent != nil,
			jtq.withJob != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &JobTalent{config: jtq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, jtq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := jtq.withTalent; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*JobTalent)
		for i := range nodes {
			fk := nodes[i].TalentID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(talent.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Talent = n
			}
		}
	}

	if query := jtq.withJob; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*JobTalent)
		for i := range nodes {
			fk := nodes[i].JobID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(job.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "job_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Job = n
			}
		}
	}

	return nodes, nil
}

func (jtq *JobTalentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := jtq.querySpec()
	return sqlgraph.CountNodes(ctx, jtq.driver, _spec)
}

func (jtq *JobTalentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := jtq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (jtq *JobTalentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   jobtalent.Table,
			Columns: jobtalent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: jobtalent.FieldID,
			},
		},
		From:   jtq.sql,
		Unique: true,
	}
	if unique := jtq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := jtq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, jobtalent.FieldID)
		for i := range fields {
			if fields[i] != jobtalent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := jtq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := jtq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := jtq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := jtq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (jtq *JobTalentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(jtq.driver.Dialect())
	t1 := builder.Table(jobtalent.Table)
	columns := jtq.fields
	if len(columns) == 0 {
		columns = jobtalent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if jtq.sql != nil {
		selector = jtq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range jtq.predicates {
		p(selector)
	}
	for _, p := range jtq.order {
		p(selector)
	}
	if offset := jtq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := jtq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// JobTalentGroupBy is the group-by builder for JobTalent entities.
type JobTalentGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (jtgb *JobTalentGroupBy) Aggregate(fns ...AggregateFunc) *JobTalentGroupBy {
	jtgb.fns = append(jtgb.fns, fns...)
	return jtgb
}

// Scan applies the group-by query and scans the result into the given value.
func (jtgb *JobTalentGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := jtgb.path(ctx)
	if err != nil {
		return err
	}
	jtgb.sql = query
	return jtgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := jtgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(jtgb.fields) > 1 {
		return nil, errors.New("ent: JobTalentGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := jtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) StringsX(ctx context.Context) []string {
	v, err := jtgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = jtgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) StringX(ctx context.Context) string {
	v, err := jtgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(jtgb.fields) > 1 {
		return nil, errors.New("ent: JobTalentGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := jtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) IntsX(ctx context.Context) []int {
	v, err := jtgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = jtgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) IntX(ctx context.Context) int {
	v, err := jtgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(jtgb.fields) > 1 {
		return nil, errors.New("ent: JobTalentGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := jtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := jtgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = jtgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) Float64X(ctx context.Context) float64 {
	v, err := jtgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(jtgb.fields) > 1 {
		return nil, errors.New("ent: JobTalentGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := jtgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := jtgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (jtgb *JobTalentGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = jtgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (jtgb *JobTalentGroupBy) BoolX(ctx context.Context) bool {
	v, err := jtgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (jtgb *JobTalentGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range jtgb.fields {
		if !jobtalent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := jtgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := jtgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (jtgb *JobTalentGroupBy) sqlQuery() *sql.Selector {
	selector := jtgb.sql.Select()
	aggregation := make([]string, 0, len(jtgb.fns))
	for _, fn := range jtgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(jtgb.fields)+len(jtgb.fns))
		for _, f := range jtgb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(jtgb.fields...)...)
}

// JobTalentSelect is the builder for selecting fields of JobTalent entities.
type JobTalentSelect struct {
	*JobTalentQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (jts *JobTalentSelect) Scan(ctx context.Context, v interface{}) error {
	if err := jts.prepareQuery(ctx); err != nil {
		return err
	}
	jts.sql = jts.JobTalentQuery.sqlQuery(ctx)
	return jts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (jts *JobTalentSelect) ScanX(ctx context.Context, v interface{}) {
	if err := jts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) Strings(ctx context.Context) ([]string, error) {
	if len(jts.fields) > 1 {
		return nil, errors.New("ent: JobTalentSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := jts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (jts *JobTalentSelect) StringsX(ctx context.Context) []string {
	v, err := jts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = jts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (jts *JobTalentSelect) StringX(ctx context.Context) string {
	v, err := jts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) Ints(ctx context.Context) ([]int, error) {
	if len(jts.fields) > 1 {
		return nil, errors.New("ent: JobTalentSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := jts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (jts *JobTalentSelect) IntsX(ctx context.Context) []int {
	v, err := jts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = jts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (jts *JobTalentSelect) IntX(ctx context.Context) int {
	v, err := jts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(jts.fields) > 1 {
		return nil, errors.New("ent: JobTalentSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := jts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (jts *JobTalentSelect) Float64sX(ctx context.Context) []float64 {
	v, err := jts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = jts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (jts *JobTalentSelect) Float64X(ctx context.Context) float64 {
	v, err := jts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(jts.fields) > 1 {
		return nil, errors.New("ent: JobTalentSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := jts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (jts *JobTalentSelect) BoolsX(ctx context.Context) []bool {
	v, err := jts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (jts *JobTalentSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = jts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{jobtalent.Label}
	default:
		err = fmt.Errorf("ent: JobTalentSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (jts *JobTalentSelect) BoolX(ctx context.Context) bool {
	v, err := jts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (jts *JobTalentSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := jts.sql.Query()
	if err := jts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
