// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/theterminalguy/tnet/ent/mission"
	"github.com/theterminalguy/tnet/ent/partner"
	"github.com/theterminalguy/tnet/ent/talent"
)

// Mission is the model entity for the Mission schema.
type Mission struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at"`
	// TalentID holds the value of the "talent_id" field.
	TalentID uuid.UUID `json:"-"`
	// PartnerID holds the value of the "partner_id" field.
	PartnerID uuid.UUID `json:"-"`
	// MissionType holds the value of the "mission_type" field.
	MissionType mission.MissionType `json:"mission_type,omitempty"`
	// StartDate holds the value of the "start_date" field.
	StartDate time.Time `json:"start_date,omitempty"`
	// EndDate holds the value of the "end_date" field.
	EndDate time.Time `json:"end_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MissionQuery when eager-loading is set.
	Edges MissionEdges `json:"edges"`
}

// MissionEdges holds the relations/edges for other nodes in the graph.
type MissionEdges struct {
	// Talent holds the value of the talent edge.
	Talent *Talent `json:"talent,omitempty"`
	// Partner holds the value of the partner edge.
	Partner *Partner `json:"partner,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// TalentOrErr returns the Talent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MissionEdges) TalentOrErr() (*Talent, error) {
	if e.loadedTypes[0] {
		if e.Talent == nil {
			// The edge talent was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: talent.Label}
		}
		return e.Talent, nil
	}
	return nil, &NotLoadedError{edge: "talent"}
}

// PartnerOrErr returns the Partner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MissionEdges) PartnerOrErr() (*Partner, error) {
	if e.loadedTypes[1] {
		if e.Partner == nil {
			// The edge partner was loaded in eager-loading,
			// but was not found.
			return nil, &NotFoundError{label: partner.Label}
		}
		return e.Partner, nil
	}
	return nil, &NotLoadedError{edge: "partner"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Mission) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case mission.FieldMissionType:
			values[i] = new(sql.NullString)
		case mission.FieldCreatedAt, mission.FieldUpdatedAt, mission.FieldDeletedAt, mission.FieldStartDate, mission.FieldEndDate:
			values[i] = new(sql.NullTime)
		case mission.FieldID, mission.FieldTalentID, mission.FieldPartnerID:
			values[i] = new(uuid.UUID)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Mission", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Mission fields.
func (m *Mission) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case mission.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				m.ID = *value
			}
		case mission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				m.CreatedAt = value.Time
			}
		case mission.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				m.UpdatedAt = value.Time
			}
		case mission.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				m.DeletedAt = new(time.Time)
				*m.DeletedAt = value.Time
			}
		case mission.FieldTalentID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field talent_id", values[i])
			} else if value != nil {
				m.TalentID = *value
			}
		case mission.FieldPartnerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field partner_id", values[i])
			} else if value != nil {
				m.PartnerID = *value
			}
		case mission.FieldMissionType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mission_type", values[i])
			} else if value.Valid {
				m.MissionType = mission.MissionType(value.String)
			}
		case mission.FieldStartDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_date", values[i])
			} else if value.Valid {
				m.StartDate = value.Time
			}
		case mission.FieldEndDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_date", values[i])
			} else if value.Valid {
				m.EndDate = value.Time
			}
		}
	}
	return nil
}

// QueryTalent queries the "talent" edge of the Mission entity.
func (m *Mission) QueryTalent() *TalentQuery {
	return (&MissionClient{config: m.config}).QueryTalent(m)
}

// QueryPartner queries the "partner" edge of the Mission entity.
func (m *Mission) QueryPartner() *PartnerQuery {
	return (&MissionClient{config: m.config}).QueryPartner(m)
}

// Update returns a builder for updating this Mission.
// Note that you need to call Mission.Unwrap() before calling this method if this Mission
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Mission) Update() *MissionUpdateOne {
	return (&MissionClient{config: m.config}).UpdateOne(m)
}

// Unwrap unwraps the Mission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Mission) Unwrap() *Mission {
	tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Mission is not a transactional entity")
	}
	m.config.driver = tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Mission) String() string {
	var builder strings.Builder
	builder.WriteString("Mission(")
	builder.WriteString(fmt.Sprintf("id=%v", m.ID))
	builder.WriteString(", created_at=")
	builder.WriteString(m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", updated_at=")
	builder.WriteString(m.UpdatedAt.Format(time.ANSIC))
	if v := m.DeletedAt; v != nil {
		builder.WriteString(", deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", talent_id=")
	builder.WriteString(fmt.Sprintf("%v", m.TalentID))
	builder.WriteString(", partner_id=")
	builder.WriteString(fmt.Sprintf("%v", m.PartnerID))
	builder.WriteString(", mission_type=")
	builder.WriteString(fmt.Sprintf("%v", m.MissionType))
	builder.WriteString(", start_date=")
	builder.WriteString(m.StartDate.Format(time.ANSIC))
	builder.WriteString(", end_date=")
	builder.WriteString(m.EndDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Missions is a parsable slice of Mission.
type Missions []*Mission

func (m Missions) config(cfg config) {
	for _i := range m {
		m[_i].config = cfg
	}
}
