// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/oauth2client"
	"github.com/10hourlabs/tentn/ent/oauth2token"
	"github.com/10hourlabs/tentn/ent/user"
	"github.com/google/uuid"
)

// Oauth2TokenCreate is the builder for creating a Oauth2Token entity.
type Oauth2TokenCreate struct {
	config
	mutation *Oauth2TokenMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (oc *Oauth2TokenCreate) SetCreatedAt(t time.Time) *Oauth2TokenCreate {
	oc.mutation.SetCreatedAt(t)
	return oc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableCreatedAt(t *time.Time) *Oauth2TokenCreate {
	if t != nil {
		oc.SetCreatedAt(*t)
	}
	return oc
}

// SetUpdatedAt sets the "updated_at" field.
func (oc *Oauth2TokenCreate) SetUpdatedAt(t time.Time) *Oauth2TokenCreate {
	oc.mutation.SetUpdatedAt(t)
	return oc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableUpdatedAt(t *time.Time) *Oauth2TokenCreate {
	if t != nil {
		oc.SetUpdatedAt(*t)
	}
	return oc
}

// SetDeletedAt sets the "deleted_at" field.
func (oc *Oauth2TokenCreate) SetDeletedAt(t time.Time) *Oauth2TokenCreate {
	oc.mutation.SetDeletedAt(t)
	return oc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableDeletedAt(t *time.Time) *Oauth2TokenCreate {
	if t != nil {
		oc.SetDeletedAt(*t)
	}
	return oc
}

// SetUserID sets the "user_id" field.
func (oc *Oauth2TokenCreate) SetUserID(u uuid.UUID) *Oauth2TokenCreate {
	oc.mutation.SetUserID(u)
	return oc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableUserID(u *uuid.UUID) *Oauth2TokenCreate {
	if u != nil {
		oc.SetUserID(*u)
	}
	return oc
}

// SetOauth2ClientID sets the "oauth2_client_id" field.
func (oc *Oauth2TokenCreate) SetOauth2ClientID(u uuid.UUID) *Oauth2TokenCreate {
	oc.mutation.SetOauth2ClientID(u)
	return oc
}

// SetNillableOauth2ClientID sets the "oauth2_client_id" field if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableOauth2ClientID(u *uuid.UUID) *Oauth2TokenCreate {
	if u != nil {
		oc.SetOauth2ClientID(*u)
	}
	return oc
}

// SetRedirectURI sets the "redirect_uri" field.
func (oc *Oauth2TokenCreate) SetRedirectURI(s string) *Oauth2TokenCreate {
	oc.mutation.SetRedirectURI(s)
	return oc
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableRedirectURI(s *string) *Oauth2TokenCreate {
	if s != nil {
		oc.SetRedirectURI(*s)
	}
	return oc
}

// SetScopes sets the "scopes" field.
func (oc *Oauth2TokenCreate) SetScopes(s string) *Oauth2TokenCreate {
	oc.mutation.SetScopes(s)
	return oc
}

// SetCode sets the "code" field.
func (oc *Oauth2TokenCreate) SetCode(s string) *Oauth2TokenCreate {
	oc.mutation.SetCode(s)
	return oc
}

// SetCodeChallenge sets the "code_challenge" field.
func (oc *Oauth2TokenCreate) SetCodeChallenge(s string) *Oauth2TokenCreate {
	oc.mutation.SetCodeChallenge(s)
	return oc
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (oc *Oauth2TokenCreate) SetCodeChallengeMethod(s string) *Oauth2TokenCreate {
	oc.mutation.SetCodeChallengeMethod(s)
	return oc
}

// SetCodeCreatedAt sets the "code_created_at" field.
func (oc *Oauth2TokenCreate) SetCodeCreatedAt(s string) *Oauth2TokenCreate {
	oc.mutation.SetCodeCreatedAt(s)
	return oc
}

// SetCodeExpiresAt sets the "code_expires_at" field.
func (oc *Oauth2TokenCreate) SetCodeExpiresAt(s string) *Oauth2TokenCreate {
	oc.mutation.SetCodeExpiresAt(s)
	return oc
}

// SetAccessToken sets the "access_token" field.
func (oc *Oauth2TokenCreate) SetAccessToken(s string) *Oauth2TokenCreate {
	oc.mutation.SetAccessToken(s)
	return oc
}

// SetAccessTokenCreatedAt sets the "access_token_created_at" field.
func (oc *Oauth2TokenCreate) SetAccessTokenCreatedAt(s string) *Oauth2TokenCreate {
	oc.mutation.SetAccessTokenCreatedAt(s)
	return oc
}

// SetAccessTokenExpiresAt sets the "access_token_expires_at" field.
func (oc *Oauth2TokenCreate) SetAccessTokenExpiresAt(s string) *Oauth2TokenCreate {
	oc.mutation.SetAccessTokenExpiresAt(s)
	return oc
}

// SetRefreshToken sets the "refresh_token" field.
func (oc *Oauth2TokenCreate) SetRefreshToken(s string) *Oauth2TokenCreate {
	oc.mutation.SetRefreshToken(s)
	return oc
}

// SetRefreshTokenCreatedAt sets the "refresh_token_created_at" field.
func (oc *Oauth2TokenCreate) SetRefreshTokenCreatedAt(s string) *Oauth2TokenCreate {
	oc.mutation.SetRefreshTokenCreatedAt(s)
	return oc
}

// SetRefreshTokenExpiresAt sets the "refresh_token_expires_at" field.
func (oc *Oauth2TokenCreate) SetRefreshTokenExpiresAt(s string) *Oauth2TokenCreate {
	oc.mutation.SetRefreshTokenExpiresAt(s)
	return oc
}

// SetID sets the "id" field.
func (oc *Oauth2TokenCreate) SetID(u uuid.UUID) *Oauth2TokenCreate {
	oc.mutation.SetID(u)
	return oc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableID(u *uuid.UUID) *Oauth2TokenCreate {
	if u != nil {
		oc.SetID(*u)
	}
	return oc
}

// SetUser sets the "user" edge to the User entity.
func (oc *Oauth2TokenCreate) SetUser(u *User) *Oauth2TokenCreate {
	return oc.SetUserID(u.ID)
}

// SetOauth2clientID sets the "oauth2client" edge to the Oauth2Client entity by ID.
func (oc *Oauth2TokenCreate) SetOauth2clientID(id uuid.UUID) *Oauth2TokenCreate {
	oc.mutation.SetOauth2clientID(id)
	return oc
}

// SetNillableOauth2clientID sets the "oauth2client" edge to the Oauth2Client entity by ID if the given value is not nil.
func (oc *Oauth2TokenCreate) SetNillableOauth2clientID(id *uuid.UUID) *Oauth2TokenCreate {
	if id != nil {
		oc = oc.SetOauth2clientID(*id)
	}
	return oc
}

// SetOauth2client sets the "oauth2client" edge to the Oauth2Client entity.
func (oc *Oauth2TokenCreate) SetOauth2client(o *Oauth2Client) *Oauth2TokenCreate {
	return oc.SetOauth2clientID(o.ID)
}

// Mutation returns the Oauth2TokenMutation object of the builder.
func (oc *Oauth2TokenCreate) Mutation() *Oauth2TokenMutation {
	return oc.mutation
}

// Save creates the Oauth2Token in the database.
func (oc *Oauth2TokenCreate) Save(ctx context.Context) (*Oauth2Token, error) {
	var (
		err  error
		node *Oauth2Token
	)
	oc.defaults()
	if len(oc.hooks) == 0 {
		if err = oc.check(); err != nil {
			return nil, err
		}
		node, err = oc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*Oauth2TokenMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = oc.check(); err != nil {
				return nil, err
			}
			oc.mutation = mutation
			if node, err = oc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(oc.hooks) - 1; i >= 0; i-- {
			if oc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = oc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, oc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (oc *Oauth2TokenCreate) SaveX(ctx context.Context) *Oauth2Token {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *Oauth2TokenCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *Oauth2TokenCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *Oauth2TokenCreate) defaults() {
	if _, ok := oc.mutation.CreatedAt(); !ok {
		v := oauth2token.DefaultCreatedAt()
		oc.mutation.SetCreatedAt(v)
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		v := oauth2token.DefaultUpdatedAt()
		oc.mutation.SetUpdatedAt(v)
	}
	if _, ok := oc.mutation.ID(); !ok {
		v := oauth2token.DefaultID()
		oc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (oc *Oauth2TokenCreate) check() error {
	if _, ok := oc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Oauth2Token.created_at"`)}
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Oauth2Token.updated_at"`)}
	}
	if _, ok := oc.mutation.Scopes(); !ok {
		return &ValidationError{Name: "scopes", err: errors.New(`ent: missing required field "Oauth2Token.scopes"`)}
	}
	if _, ok := oc.mutation.Code(); !ok {
		return &ValidationError{Name: "code", err: errors.New(`ent: missing required field "Oauth2Token.code"`)}
	}
	if _, ok := oc.mutation.CodeChallenge(); !ok {
		return &ValidationError{Name: "code_challenge", err: errors.New(`ent: missing required field "Oauth2Token.code_challenge"`)}
	}
	if _, ok := oc.mutation.CodeChallengeMethod(); !ok {
		return &ValidationError{Name: "code_challenge_method", err: errors.New(`ent: missing required field "Oauth2Token.code_challenge_method"`)}
	}
	if _, ok := oc.mutation.CodeCreatedAt(); !ok {
		return &ValidationError{Name: "code_created_at", err: errors.New(`ent: missing required field "Oauth2Token.code_created_at"`)}
	}
	if _, ok := oc.mutation.CodeExpiresAt(); !ok {
		return &ValidationError{Name: "code_expires_at", err: errors.New(`ent: missing required field "Oauth2Token.code_expires_at"`)}
	}
	if _, ok := oc.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "Oauth2Token.access_token"`)}
	}
	if _, ok := oc.mutation.AccessTokenCreatedAt(); !ok {
		return &ValidationError{Name: "access_token_created_at", err: errors.New(`ent: missing required field "Oauth2Token.access_token_created_at"`)}
	}
	if _, ok := oc.mutation.AccessTokenExpiresAt(); !ok {
		return &ValidationError{Name: "access_token_expires_at", err: errors.New(`ent: missing required field "Oauth2Token.access_token_expires_at"`)}
	}
	if _, ok := oc.mutation.RefreshToken(); !ok {
		return &ValidationError{Name: "refresh_token", err: errors.New(`ent: missing required field "Oauth2Token.refresh_token"`)}
	}
	if _, ok := oc.mutation.RefreshTokenCreatedAt(); !ok {
		return &ValidationError{Name: "refresh_token_created_at", err: errors.New(`ent: missing required field "Oauth2Token.refresh_token_created_at"`)}
	}
	if _, ok := oc.mutation.RefreshTokenExpiresAt(); !ok {
		return &ValidationError{Name: "refresh_token_expires_at", err: errors.New(`ent: missing required field "Oauth2Token.refresh_token_expires_at"`)}
	}
	return nil
}

func (oc *Oauth2TokenCreate) sqlSave(ctx context.Context) (*Oauth2Token, error) {
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (oc *Oauth2TokenCreate) createSpec() (*Oauth2Token, *sqlgraph.CreateSpec) {
	var (
		_node = &Oauth2Token{config: oc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: oauth2token.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: oauth2token.FieldID,
			},
		}
	)
	if id, ok := oc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := oc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: oauth2token.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := oc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: oauth2token.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := oc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: oauth2token.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := oc.mutation.RedirectURI(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldRedirectURI,
		})
		_node.RedirectURI = value
	}
	if value, ok := oc.mutation.Scopes(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldScopes,
		})
		_node.Scopes = value
	}
	if value, ok := oc.mutation.Code(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldCode,
		})
		_node.Code = value
	}
	if value, ok := oc.mutation.CodeChallenge(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldCodeChallenge,
		})
		_node.CodeChallenge = value
	}
	if value, ok := oc.mutation.CodeChallengeMethod(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldCodeChallengeMethod,
		})
		_node.CodeChallengeMethod = value
	}
	if value, ok := oc.mutation.CodeCreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldCodeCreatedAt,
		})
		_node.CodeCreatedAt = value
	}
	if value, ok := oc.mutation.CodeExpiresAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldCodeExpiresAt,
		})
		_node.CodeExpiresAt = value
	}
	if value, ok := oc.mutation.AccessToken(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldAccessToken,
		})
		_node.AccessToken = value
	}
	if value, ok := oc.mutation.AccessTokenCreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldAccessTokenCreatedAt,
		})
		_node.AccessTokenCreatedAt = value
	}
	if value, ok := oc.mutation.AccessTokenExpiresAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldAccessTokenExpiresAt,
		})
		_node.AccessTokenExpiresAt = value
	}
	if value, ok := oc.mutation.RefreshToken(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldRefreshToken,
		})
		_node.RefreshToken = value
	}
	if value, ok := oc.mutation.RefreshTokenCreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldRefreshTokenCreatedAt,
		})
		_node.RefreshTokenCreatedAt = value
	}
	if value, ok := oc.mutation.RefreshTokenExpiresAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: oauth2token.FieldRefreshTokenExpiresAt,
		})
		_node.RefreshTokenExpiresAt = value
	}
	if nodes := oc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauth2token.UserTable,
			Columns: []string{oauth2token.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := oc.mutation.Oauth2clientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauth2token.Oauth2clientTable,
			Columns: []string{oauth2token.Oauth2clientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: oauth2client.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.Oauth2ClientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// Oauth2TokenCreateBulk is the builder for creating many Oauth2Token entities in bulk.
type Oauth2TokenCreateBulk struct {
	config
	builders []*Oauth2TokenCreate
}

// Save creates the Oauth2Token entities in the database.
func (ocb *Oauth2TokenCreateBulk) Save(ctx context.Context) ([]*Oauth2Token, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Oauth2Token, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*Oauth2TokenMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *Oauth2TokenCreateBulk) SaveX(ctx context.Context) []*Oauth2Token {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *Oauth2TokenCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *Oauth2TokenCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}
