// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/mission"
	"github.com/10hourlabs/tentn/ent/partner"
	"github.com/google/uuid"
)

// PartnerCreate is the builder for creating a Partner entity.
type PartnerCreate struct {
	config
	mutation *PartnerMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (pc *PartnerCreate) SetCreatedAt(t time.Time) *PartnerCreate {
	pc.mutation.SetCreatedAt(t)
	return pc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (pc *PartnerCreate) SetNillableCreatedAt(t *time.Time) *PartnerCreate {
	if t != nil {
		pc.SetCreatedAt(*t)
	}
	return pc
}

// SetUpdatedAt sets the "updated_at" field.
func (pc *PartnerCreate) SetUpdatedAt(t time.Time) *PartnerCreate {
	pc.mutation.SetUpdatedAt(t)
	return pc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (pc *PartnerCreate) SetNillableUpdatedAt(t *time.Time) *PartnerCreate {
	if t != nil {
		pc.SetUpdatedAt(*t)
	}
	return pc
}

// SetDeletedAt sets the "deleted_at" field.
func (pc *PartnerCreate) SetDeletedAt(t time.Time) *PartnerCreate {
	pc.mutation.SetDeletedAt(t)
	return pc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pc *PartnerCreate) SetNillableDeletedAt(t *time.Time) *PartnerCreate {
	if t != nil {
		pc.SetDeletedAt(*t)
	}
	return pc
}

// SetCompanyName sets the "CompanyName" field.
func (pc *PartnerCreate) SetCompanyName(s string) *PartnerCreate {
	pc.mutation.SetCompanyName(s)
	return pc
}

// SetCompanyLocation sets the "CompanyLocation" field.
func (pc *PartnerCreate) SetCompanyLocation(s string) *PartnerCreate {
	pc.mutation.SetCompanyLocation(s)
	return pc
}

// SetContactPersonName sets the "ContactPersonName" field.
func (pc *PartnerCreate) SetContactPersonName(s string) *PartnerCreate {
	pc.mutation.SetContactPersonName(s)
	return pc
}

// SetContactPersonPhoneNumber sets the "ContactPersonPhoneNumber" field.
func (pc *PartnerCreate) SetContactPersonPhoneNumber(s string) *PartnerCreate {
	pc.mutation.SetContactPersonPhoneNumber(s)
	return pc
}

// SetContactPersonEmail sets the "ContactPersonEmail" field.
func (pc *PartnerCreate) SetContactPersonEmail(s string) *PartnerCreate {
	pc.mutation.SetContactPersonEmail(s)
	return pc
}

// SetWebsiteUrl sets the "WebsiteUrl" field.
func (pc *PartnerCreate) SetWebsiteUrl(s string) *PartnerCreate {
	pc.mutation.SetWebsiteUrl(s)
	return pc
}

// SetID sets the "id" field.
func (pc *PartnerCreate) SetID(u uuid.UUID) *PartnerCreate {
	pc.mutation.SetID(u)
	return pc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (pc *PartnerCreate) SetNillableID(u *uuid.UUID) *PartnerCreate {
	if u != nil {
		pc.SetID(*u)
	}
	return pc
}

// AddMissionIDs adds the "missions" edge to the Mission entity by IDs.
func (pc *PartnerCreate) AddMissionIDs(ids ...uuid.UUID) *PartnerCreate {
	pc.mutation.AddMissionIDs(ids...)
	return pc
}

// AddMissions adds the "missions" edges to the Mission entity.
func (pc *PartnerCreate) AddMissions(m ...*Mission) *PartnerCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return pc.AddMissionIDs(ids...)
}

// Mutation returns the PartnerMutation object of the builder.
func (pc *PartnerCreate) Mutation() *PartnerMutation {
	return pc.mutation
}

// Save creates the Partner in the database.
func (pc *PartnerCreate) Save(ctx context.Context) (*Partner, error) {
	var (
		err  error
		node *Partner
	)
	pc.defaults()
	if len(pc.hooks) == 0 {
		if err = pc.check(); err != nil {
			return nil, err
		}
		node, err = pc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PartnerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = pc.check(); err != nil {
				return nil, err
			}
			pc.mutation = mutation
			if node, err = pc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(pc.hooks) - 1; i >= 0; i-- {
			if pc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (pc *PartnerCreate) SaveX(ctx context.Context) *Partner {
	v, err := pc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pc *PartnerCreate) Exec(ctx context.Context) error {
	_, err := pc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pc *PartnerCreate) ExecX(ctx context.Context) {
	if err := pc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pc *PartnerCreate) defaults() {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		v := partner.DefaultCreatedAt()
		pc.mutation.SetCreatedAt(v)
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		v := partner.DefaultUpdatedAt()
		pc.mutation.SetUpdatedAt(v)
	}
	if _, ok := pc.mutation.ID(); !ok {
		v := partner.DefaultID()
		pc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (pc *PartnerCreate) check() error {
	if _, ok := pc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Partner.created_at"`)}
	}
	if _, ok := pc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Partner.updated_at"`)}
	}
	if _, ok := pc.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "CompanyName", err: errors.New(`ent: missing required field "Partner.CompanyName"`)}
	}
	if _, ok := pc.mutation.CompanyLocation(); !ok {
		return &ValidationError{Name: "CompanyLocation", err: errors.New(`ent: missing required field "Partner.CompanyLocation"`)}
	}
	if _, ok := pc.mutation.ContactPersonName(); !ok {
		return &ValidationError{Name: "ContactPersonName", err: errors.New(`ent: missing required field "Partner.ContactPersonName"`)}
	}
	if _, ok := pc.mutation.ContactPersonPhoneNumber(); !ok {
		return &ValidationError{Name: "ContactPersonPhoneNumber", err: errors.New(`ent: missing required field "Partner.ContactPersonPhoneNumber"`)}
	}
	if _, ok := pc.mutation.ContactPersonEmail(); !ok {
		return &ValidationError{Name: "ContactPersonEmail", err: errors.New(`ent: missing required field "Partner.ContactPersonEmail"`)}
	}
	if _, ok := pc.mutation.WebsiteUrl(); !ok {
		return &ValidationError{Name: "WebsiteUrl", err: errors.New(`ent: missing required field "Partner.WebsiteUrl"`)}
	}
	return nil
}

func (pc *PartnerCreate) sqlSave(ctx context.Context) (*Partner, error) {
	_node, _spec := pc.createSpec()
	if err := sqlgraph.CreateNode(ctx, pc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (pc *PartnerCreate) createSpec() (*Partner, *sqlgraph.CreateSpec) {
	var (
		_node = &Partner{config: pc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: partner.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: partner.FieldID,
			},
		}
	)
	_spec.OnConflict = pc.conflict
	if id, ok := pc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := pc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: partner.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := pc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: partner.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := pc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: partner.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := pc.mutation.CompanyName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partner.FieldCompanyName,
		})
		_node.CompanyName = value
	}
	if value, ok := pc.mutation.CompanyLocation(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partner.FieldCompanyLocation,
		})
		_node.CompanyLocation = value
	}
	if value, ok := pc.mutation.ContactPersonName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partner.FieldContactPersonName,
		})
		_node.ContactPersonName = value
	}
	if value, ok := pc.mutation.ContactPersonPhoneNumber(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partner.FieldContactPersonPhoneNumber,
		})
		_node.ContactPersonPhoneNumber = value
	}
	if value, ok := pc.mutation.ContactPersonEmail(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partner.FieldContactPersonEmail,
		})
		_node.ContactPersonEmail = value
	}
	if value, ok := pc.mutation.WebsiteUrl(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: partner.FieldWebsiteUrl,
		})
		_node.WebsiteUrl = value
	}
	if nodes := pc.mutation.MissionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   partner.MissionsTable,
			Columns: []string{partner.MissionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: mission.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Partner.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PartnerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (pc *PartnerCreate) OnConflict(opts ...sql.ConflictOption) *PartnerUpsertOne {
	pc.conflict = opts
	return &PartnerUpsertOne{
		create: pc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Partner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (pc *PartnerCreate) OnConflictColumns(columns ...string) *PartnerUpsertOne {
	pc.conflict = append(pc.conflict, sql.ConflictColumns(columns...))
	return &PartnerUpsertOne{
		create: pc,
	}
}

type (
	// PartnerUpsertOne is the builder for "upsert"-ing
	//  one Partner node.
	PartnerUpsertOne struct {
		create *PartnerCreate
	}

	// PartnerUpsert is the "OnConflict" setter.
	PartnerUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *PartnerUpsert) SetCreatedAt(v time.Time) *PartnerUpsert {
	u.Set(partner.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateCreatedAt() *PartnerUpsert {
	u.SetExcluded(partner.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PartnerUpsert) SetUpdatedAt(v time.Time) *PartnerUpsert {
	u.Set(partner.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateUpdatedAt() *PartnerUpsert {
	u.SetExcluded(partner.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PartnerUpsert) SetDeletedAt(v time.Time) *PartnerUpsert {
	u.Set(partner.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateDeletedAt() *PartnerUpsert {
	u.SetExcluded(partner.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PartnerUpsert) ClearDeletedAt() *PartnerUpsert {
	u.SetNull(partner.FieldDeletedAt)
	return u
}

// SetCompanyName sets the "CompanyName" field.
func (u *PartnerUpsert) SetCompanyName(v string) *PartnerUpsert {
	u.Set(partner.FieldCompanyName, v)
	return u
}

// UpdateCompanyName sets the "CompanyName" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateCompanyName() *PartnerUpsert {
	u.SetExcluded(partner.FieldCompanyName)
	return u
}

// SetCompanyLocation sets the "CompanyLocation" field.
func (u *PartnerUpsert) SetCompanyLocation(v string) *PartnerUpsert {
	u.Set(partner.FieldCompanyLocation, v)
	return u
}

// UpdateCompanyLocation sets the "CompanyLocation" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateCompanyLocation() *PartnerUpsert {
	u.SetExcluded(partner.FieldCompanyLocation)
	return u
}

// SetContactPersonName sets the "ContactPersonName" field.
func (u *PartnerUpsert) SetContactPersonName(v string) *PartnerUpsert {
	u.Set(partner.FieldContactPersonName, v)
	return u
}

// UpdateContactPersonName sets the "ContactPersonName" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateContactPersonName() *PartnerUpsert {
	u.SetExcluded(partner.FieldContactPersonName)
	return u
}

// SetContactPersonPhoneNumber sets the "ContactPersonPhoneNumber" field.
func (u *PartnerUpsert) SetContactPersonPhoneNumber(v string) *PartnerUpsert {
	u.Set(partner.FieldContactPersonPhoneNumber, v)
	return u
}

// UpdateContactPersonPhoneNumber sets the "ContactPersonPhoneNumber" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateContactPersonPhoneNumber() *PartnerUpsert {
	u.SetExcluded(partner.FieldContactPersonPhoneNumber)
	return u
}

// SetContactPersonEmail sets the "ContactPersonEmail" field.
func (u *PartnerUpsert) SetContactPersonEmail(v string) *PartnerUpsert {
	u.Set(partner.FieldContactPersonEmail, v)
	return u
}

// UpdateContactPersonEmail sets the "ContactPersonEmail" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateContactPersonEmail() *PartnerUpsert {
	u.SetExcluded(partner.FieldContactPersonEmail)
	return u
}

// SetWebsiteUrl sets the "WebsiteUrl" field.
func (u *PartnerUpsert) SetWebsiteUrl(v string) *PartnerUpsert {
	u.Set(partner.FieldWebsiteUrl, v)
	return u
}

// UpdateWebsiteUrl sets the "WebsiteUrl" field to the value that was provided on create.
func (u *PartnerUpsert) UpdateWebsiteUrl() *PartnerUpsert {
	u.SetExcluded(partner.FieldWebsiteUrl)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.Partner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(partner.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *PartnerUpsertOne) UpdateNewValues() *PartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(partner.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(partner.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Partner.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *PartnerUpsertOne) Ignore() *PartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PartnerUpsertOne) DoNothing() *PartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PartnerCreate.OnConflict
// documentation for more info.
func (u *PartnerUpsertOne) Update(set func(*PartnerUpsert)) *PartnerUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PartnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *PartnerUpsertOne) SetCreatedAt(v time.Time) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateCreatedAt() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PartnerUpsertOne) SetUpdatedAt(v time.Time) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateUpdatedAt() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PartnerUpsertOne) SetDeletedAt(v time.Time) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateDeletedAt() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PartnerUpsertOne) ClearDeletedAt() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCompanyName sets the "CompanyName" field.
func (u *PartnerUpsertOne) SetCompanyName(v string) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "CompanyName" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateCompanyName() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateCompanyName()
	})
}

// SetCompanyLocation sets the "CompanyLocation" field.
func (u *PartnerUpsertOne) SetCompanyLocation(v string) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetCompanyLocation(v)
	})
}

// UpdateCompanyLocation sets the "CompanyLocation" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateCompanyLocation() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateCompanyLocation()
	})
}

// SetContactPersonName sets the "ContactPersonName" field.
func (u *PartnerUpsertOne) SetContactPersonName(v string) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetContactPersonName(v)
	})
}

// UpdateContactPersonName sets the "ContactPersonName" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateContactPersonName() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateContactPersonName()
	})
}

// SetContactPersonPhoneNumber sets the "ContactPersonPhoneNumber" field.
func (u *PartnerUpsertOne) SetContactPersonPhoneNumber(v string) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetContactPersonPhoneNumber(v)
	})
}

// UpdateContactPersonPhoneNumber sets the "ContactPersonPhoneNumber" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateContactPersonPhoneNumber() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateContactPersonPhoneNumber()
	})
}

// SetContactPersonEmail sets the "ContactPersonEmail" field.
func (u *PartnerUpsertOne) SetContactPersonEmail(v string) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetContactPersonEmail(v)
	})
}

// UpdateContactPersonEmail sets the "ContactPersonEmail" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateContactPersonEmail() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateContactPersonEmail()
	})
}

// SetWebsiteUrl sets the "WebsiteUrl" field.
func (u *PartnerUpsertOne) SetWebsiteUrl(v string) *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.SetWebsiteUrl(v)
	})
}

// UpdateWebsiteUrl sets the "WebsiteUrl" field to the value that was provided on create.
func (u *PartnerUpsertOne) UpdateWebsiteUrl() *PartnerUpsertOne {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateWebsiteUrl()
	})
}

// Exec executes the query.
func (u *PartnerUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PartnerCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PartnerUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *PartnerUpsertOne) ID(ctx context.Context) (id uuid.UUID, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: PartnerUpsertOne.ID is not supported by MySQL driver. Use PartnerUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *PartnerUpsertOne) IDX(ctx context.Context) uuid.UUID {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// PartnerCreateBulk is the builder for creating many Partner entities in bulk.
type PartnerCreateBulk struct {
	config
	builders []*PartnerCreate
	conflict []sql.ConflictOption
}

// Save creates the Partner entities in the database.
func (pcb *PartnerCreateBulk) Save(ctx context.Context) ([]*Partner, error) {
	specs := make([]*sqlgraph.CreateSpec, len(pcb.builders))
	nodes := make([]*Partner, len(pcb.builders))
	mutators := make([]Mutator, len(pcb.builders))
	for i := range pcb.builders {
		func(i int, root context.Context) {
			builder := pcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PartnerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, pcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = pcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, pcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, pcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (pcb *PartnerCreateBulk) SaveX(ctx context.Context) []*Partner {
	v, err := pcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (pcb *PartnerCreateBulk) Exec(ctx context.Context) error {
	_, err := pcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pcb *PartnerCreateBulk) ExecX(ctx context.Context) {
	if err := pcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Partner.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.PartnerUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
//
func (pcb *PartnerCreateBulk) OnConflict(opts ...sql.ConflictOption) *PartnerUpsertBulk {
	pcb.conflict = opts
	return &PartnerUpsertBulk{
		create: pcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Partner.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (pcb *PartnerCreateBulk) OnConflictColumns(columns ...string) *PartnerUpsertBulk {
	pcb.conflict = append(pcb.conflict, sql.ConflictColumns(columns...))
	return &PartnerUpsertBulk{
		create: pcb,
	}
}

// PartnerUpsertBulk is the builder for "upsert"-ing
// a bulk of Partner nodes.
type PartnerUpsertBulk struct {
	create *PartnerCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Partner.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(partner.FieldID)
//			}),
//		).
//		Exec(ctx)
//
func (u *PartnerUpsertBulk) UpdateNewValues() *PartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(partner.FieldID)
				return
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(partner.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Partner.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *PartnerUpsertBulk) Ignore() *PartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *PartnerUpsertBulk) DoNothing() *PartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the PartnerCreateBulk.OnConflict
// documentation for more info.
func (u *PartnerUpsertBulk) Update(set func(*PartnerUpsert)) *PartnerUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&PartnerUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *PartnerUpsertBulk) SetCreatedAt(v time.Time) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateCreatedAt() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *PartnerUpsertBulk) SetUpdatedAt(v time.Time) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateUpdatedAt() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *PartnerUpsertBulk) SetDeletedAt(v time.Time) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateDeletedAt() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *PartnerUpsertBulk) ClearDeletedAt() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.ClearDeletedAt()
	})
}

// SetCompanyName sets the "CompanyName" field.
func (u *PartnerUpsertBulk) SetCompanyName(v string) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "CompanyName" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateCompanyName() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateCompanyName()
	})
}

// SetCompanyLocation sets the "CompanyLocation" field.
func (u *PartnerUpsertBulk) SetCompanyLocation(v string) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetCompanyLocation(v)
	})
}

// UpdateCompanyLocation sets the "CompanyLocation" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateCompanyLocation() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateCompanyLocation()
	})
}

// SetContactPersonName sets the "ContactPersonName" field.
func (u *PartnerUpsertBulk) SetContactPersonName(v string) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetContactPersonName(v)
	})
}

// UpdateContactPersonName sets the "ContactPersonName" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateContactPersonName() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateContactPersonName()
	})
}

// SetContactPersonPhoneNumber sets the "ContactPersonPhoneNumber" field.
func (u *PartnerUpsertBulk) SetContactPersonPhoneNumber(v string) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetContactPersonPhoneNumber(v)
	})
}

// UpdateContactPersonPhoneNumber sets the "ContactPersonPhoneNumber" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateContactPersonPhoneNumber() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateContactPersonPhoneNumber()
	})
}

// SetContactPersonEmail sets the "ContactPersonEmail" field.
func (u *PartnerUpsertBulk) SetContactPersonEmail(v string) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetContactPersonEmail(v)
	})
}

// UpdateContactPersonEmail sets the "ContactPersonEmail" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateContactPersonEmail() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateContactPersonEmail()
	})
}

// SetWebsiteUrl sets the "WebsiteUrl" field.
func (u *PartnerUpsertBulk) SetWebsiteUrl(v string) *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.SetWebsiteUrl(v)
	})
}

// UpdateWebsiteUrl sets the "WebsiteUrl" field to the value that was provided on create.
func (u *PartnerUpsertBulk) UpdateWebsiteUrl() *PartnerUpsertBulk {
	return u.Update(func(s *PartnerUpsert) {
		s.UpdateWebsiteUrl()
	})
}

// Exec executes the query.
func (u *PartnerUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the PartnerCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for PartnerCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *PartnerUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
