// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/portfoliolink"
	"github.com/10hourlabs/tentn/ent/predicate"
	"github.com/10hourlabs/tentn/ent/talent"
	"github.com/google/uuid"
)

// PortfolioLinkUpdate is the builder for updating PortfolioLink entities.
type PortfolioLinkUpdate struct {
	config
	hooks    []Hook
	mutation *PortfolioLinkMutation
}

// Where appends a list predicates to the PortfolioLinkUpdate builder.
func (plu *PortfolioLinkUpdate) Where(ps ...predicate.PortfolioLink) *PortfolioLinkUpdate {
	plu.mutation.Where(ps...)
	return plu
}

// SetUpdatedAt sets the "updated_at" field.
func (plu *PortfolioLinkUpdate) SetUpdatedAt(t time.Time) *PortfolioLinkUpdate {
	plu.mutation.SetUpdatedAt(t)
	return plu
}

// SetDeletedAt sets the "deleted_at" field.
func (plu *PortfolioLinkUpdate) SetDeletedAt(t time.Time) *PortfolioLinkUpdate {
	plu.mutation.SetDeletedAt(t)
	return plu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (plu *PortfolioLinkUpdate) SetNillableDeletedAt(t *time.Time) *PortfolioLinkUpdate {
	if t != nil {
		plu.SetDeletedAt(*t)
	}
	return plu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (plu *PortfolioLinkUpdate) ClearDeletedAt() *PortfolioLinkUpdate {
	plu.mutation.ClearDeletedAt()
	return plu
}

// SetURL sets the "url" field.
func (plu *PortfolioLinkUpdate) SetURL(s string) *PortfolioLinkUpdate {
	plu.mutation.SetURL(s)
	return plu
}

// SetName sets the "name" field.
func (plu *PortfolioLinkUpdate) SetName(s string) *PortfolioLinkUpdate {
	plu.mutation.SetName(s)
	return plu
}

// SetTalentID sets the "talent_id" field.
func (plu *PortfolioLinkUpdate) SetTalentID(u uuid.UUID) *PortfolioLinkUpdate {
	plu.mutation.SetTalentID(u)
	return plu
}

// SetNillableTalentID sets the "talent_id" field if the given value is not nil.
func (plu *PortfolioLinkUpdate) SetNillableTalentID(u *uuid.UUID) *PortfolioLinkUpdate {
	if u != nil {
		plu.SetTalentID(*u)
	}
	return plu
}

// ClearTalentID clears the value of the "talent_id" field.
func (plu *PortfolioLinkUpdate) ClearTalentID() *PortfolioLinkUpdate {
	plu.mutation.ClearTalentID()
	return plu
}

// SetTalent sets the "talent" edge to the Talent entity.
func (plu *PortfolioLinkUpdate) SetTalent(t *Talent) *PortfolioLinkUpdate {
	return plu.SetTalentID(t.ID)
}

// Mutation returns the PortfolioLinkMutation object of the builder.
func (plu *PortfolioLinkUpdate) Mutation() *PortfolioLinkMutation {
	return plu.mutation
}

// ClearTalent clears the "talent" edge to the Talent entity.
func (plu *PortfolioLinkUpdate) ClearTalent() *PortfolioLinkUpdate {
	plu.mutation.ClearTalent()
	return plu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (plu *PortfolioLinkUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	plu.defaults()
	if len(plu.hooks) == 0 {
		affected, err = plu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PortfolioLinkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			plu.mutation = mutation
			affected, err = plu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(plu.hooks) - 1; i >= 0; i-- {
			if plu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = plu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, plu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (plu *PortfolioLinkUpdate) SaveX(ctx context.Context) int {
	affected, err := plu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (plu *PortfolioLinkUpdate) Exec(ctx context.Context) error {
	_, err := plu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plu *PortfolioLinkUpdate) ExecX(ctx context.Context) {
	if err := plu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (plu *PortfolioLinkUpdate) defaults() {
	if _, ok := plu.mutation.UpdatedAt(); !ok {
		v := portfoliolink.UpdateDefaultUpdatedAt()
		plu.mutation.SetUpdatedAt(v)
	}
}

func (plu *PortfolioLinkUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   portfoliolink.Table,
			Columns: portfoliolink.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: portfoliolink.FieldID,
			},
		},
	}
	if ps := plu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := plu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: portfoliolink.FieldUpdatedAt,
		})
	}
	if value, ok := plu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: portfoliolink.FieldDeletedAt,
		})
	}
	if plu.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: portfoliolink.FieldDeletedAt,
		})
	}
	if value, ok := plu.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: portfoliolink.FieldURL,
		})
	}
	if value, ok := plu.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: portfoliolink.FieldName,
		})
	}
	if plu.mutation.TalentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliolink.TalentTable,
			Columns: []string{portfoliolink.TalentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: talent.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := plu.mutation.TalentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliolink.TalentTable,
			Columns: []string{portfoliolink.TalentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: talent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, plu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfoliolink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// PortfolioLinkUpdateOne is the builder for updating a single PortfolioLink entity.
type PortfolioLinkUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PortfolioLinkMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (pluo *PortfolioLinkUpdateOne) SetUpdatedAt(t time.Time) *PortfolioLinkUpdateOne {
	pluo.mutation.SetUpdatedAt(t)
	return pluo
}

// SetDeletedAt sets the "deleted_at" field.
func (pluo *PortfolioLinkUpdateOne) SetDeletedAt(t time.Time) *PortfolioLinkUpdateOne {
	pluo.mutation.SetDeletedAt(t)
	return pluo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (pluo *PortfolioLinkUpdateOne) SetNillableDeletedAt(t *time.Time) *PortfolioLinkUpdateOne {
	if t != nil {
		pluo.SetDeletedAt(*t)
	}
	return pluo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (pluo *PortfolioLinkUpdateOne) ClearDeletedAt() *PortfolioLinkUpdateOne {
	pluo.mutation.ClearDeletedAt()
	return pluo
}

// SetURL sets the "url" field.
func (pluo *PortfolioLinkUpdateOne) SetURL(s string) *PortfolioLinkUpdateOne {
	pluo.mutation.SetURL(s)
	return pluo
}

// SetName sets the "name" field.
func (pluo *PortfolioLinkUpdateOne) SetName(s string) *PortfolioLinkUpdateOne {
	pluo.mutation.SetName(s)
	return pluo
}

// SetTalentID sets the "talent_id" field.
func (pluo *PortfolioLinkUpdateOne) SetTalentID(u uuid.UUID) *PortfolioLinkUpdateOne {
	pluo.mutation.SetTalentID(u)
	return pluo
}

// SetNillableTalentID sets the "talent_id" field if the given value is not nil.
func (pluo *PortfolioLinkUpdateOne) SetNillableTalentID(u *uuid.UUID) *PortfolioLinkUpdateOne {
	if u != nil {
		pluo.SetTalentID(*u)
	}
	return pluo
}

// ClearTalentID clears the value of the "talent_id" field.
func (pluo *PortfolioLinkUpdateOne) ClearTalentID() *PortfolioLinkUpdateOne {
	pluo.mutation.ClearTalentID()
	return pluo
}

// SetTalent sets the "talent" edge to the Talent entity.
func (pluo *PortfolioLinkUpdateOne) SetTalent(t *Talent) *PortfolioLinkUpdateOne {
	return pluo.SetTalentID(t.ID)
}

// Mutation returns the PortfolioLinkMutation object of the builder.
func (pluo *PortfolioLinkUpdateOne) Mutation() *PortfolioLinkMutation {
	return pluo.mutation
}

// ClearTalent clears the "talent" edge to the Talent entity.
func (pluo *PortfolioLinkUpdateOne) ClearTalent() *PortfolioLinkUpdateOne {
	pluo.mutation.ClearTalent()
	return pluo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (pluo *PortfolioLinkUpdateOne) Select(field string, fields ...string) *PortfolioLinkUpdateOne {
	pluo.fields = append([]string{field}, fields...)
	return pluo
}

// Save executes the query and returns the updated PortfolioLink entity.
func (pluo *PortfolioLinkUpdateOne) Save(ctx context.Context) (*PortfolioLink, error) {
	var (
		err  error
		node *PortfolioLink
	)
	pluo.defaults()
	if len(pluo.hooks) == 0 {
		node, err = pluo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PortfolioLinkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			pluo.mutation = mutation
			node, err = pluo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(pluo.hooks) - 1; i >= 0; i-- {
			if pluo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = pluo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, pluo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (pluo *PortfolioLinkUpdateOne) SaveX(ctx context.Context) *PortfolioLink {
	node, err := pluo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (pluo *PortfolioLinkUpdateOne) Exec(ctx context.Context) error {
	_, err := pluo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (pluo *PortfolioLinkUpdateOne) ExecX(ctx context.Context) {
	if err := pluo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (pluo *PortfolioLinkUpdateOne) defaults() {
	if _, ok := pluo.mutation.UpdatedAt(); !ok {
		v := portfoliolink.UpdateDefaultUpdatedAt()
		pluo.mutation.SetUpdatedAt(v)
	}
}

func (pluo *PortfolioLinkUpdateOne) sqlSave(ctx context.Context) (_node *PortfolioLink, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   portfoliolink.Table,
			Columns: portfoliolink.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: portfoliolink.FieldID,
			},
		},
	}
	id, ok := pluo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PortfolioLink.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := pluo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, portfoliolink.FieldID)
		for _, f := range fields {
			if !portfoliolink.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != portfoliolink.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := pluo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := pluo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: portfoliolink.FieldUpdatedAt,
		})
	}
	if value, ok := pluo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: portfoliolink.FieldDeletedAt,
		})
	}
	if pluo.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: portfoliolink.FieldDeletedAt,
		})
	}
	if value, ok := pluo.mutation.URL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: portfoliolink.FieldURL,
		})
	}
	if value, ok := pluo.mutation.Name(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: portfoliolink.FieldName,
		})
	}
	if pluo.mutation.TalentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliolink.TalentTable,
			Columns: []string{portfoliolink.TalentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: talent.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := pluo.mutation.TalentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliolink.TalentTable,
			Columns: []string{portfoliolink.TalentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: talent.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PortfolioLink{config: pluo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, pluo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{portfoliolink.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
