// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/applicant"
	"github.com/10hourlabs/tentn/ent/portfoliolink"
	"github.com/google/uuid"
)

// PortfolioLinkCreate is the builder for creating a PortfolioLink entity.
type PortfolioLinkCreate struct {
	config
	mutation *PortfolioLinkMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (plc *PortfolioLinkCreate) SetUUID(u uuid.UUID) *PortfolioLinkCreate {
	plc.mutation.SetUUID(u)
	return plc
}

// SetCreatedAt sets the "created_at" field.
func (plc *PortfolioLinkCreate) SetCreatedAt(t time.Time) *PortfolioLinkCreate {
	plc.mutation.SetCreatedAt(t)
	return plc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (plc *PortfolioLinkCreate) SetNillableCreatedAt(t *time.Time) *PortfolioLinkCreate {
	if t != nil {
		plc.SetCreatedAt(*t)
	}
	return plc
}

// SetUpdatedAt sets the "updated_at" field.
func (plc *PortfolioLinkCreate) SetUpdatedAt(t time.Time) *PortfolioLinkCreate {
	plc.mutation.SetUpdatedAt(t)
	return plc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (plc *PortfolioLinkCreate) SetNillableUpdatedAt(t *time.Time) *PortfolioLinkCreate {
	if t != nil {
		plc.SetUpdatedAt(*t)
	}
	return plc
}

// SetDeletedAt sets the "deleted_at" field.
func (plc *PortfolioLinkCreate) SetDeletedAt(t time.Time) *PortfolioLinkCreate {
	plc.mutation.SetDeletedAt(t)
	return plc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (plc *PortfolioLinkCreate) SetNillableDeletedAt(t *time.Time) *PortfolioLinkCreate {
	if t != nil {
		plc.SetDeletedAt(*t)
	}
	return plc
}

// SetURL sets the "url" field.
func (plc *PortfolioLinkCreate) SetURL(s string) *PortfolioLinkCreate {
	plc.mutation.SetURL(s)
	return plc
}

// SetName sets the "name" field.
func (plc *PortfolioLinkCreate) SetName(s string) *PortfolioLinkCreate {
	plc.mutation.SetName(s)
	return plc
}

// SetApplicantID sets the "applicant_id" field.
func (plc *PortfolioLinkCreate) SetApplicantID(i int) *PortfolioLinkCreate {
	plc.mutation.SetApplicantID(i)
	return plc
}

// SetNillableApplicantID sets the "applicant_id" field if the given value is not nil.
func (plc *PortfolioLinkCreate) SetNillableApplicantID(i *int) *PortfolioLinkCreate {
	if i != nil {
		plc.SetApplicantID(*i)
	}
	return plc
}

// SetID sets the "id" field.
func (plc *PortfolioLinkCreate) SetID(i int) *PortfolioLinkCreate {
	plc.mutation.SetID(i)
	return plc
}

// SetApplicant sets the "applicant" edge to the Applicant entity.
func (plc *PortfolioLinkCreate) SetApplicant(a *Applicant) *PortfolioLinkCreate {
	return plc.SetApplicantID(a.ID)
}

// Mutation returns the PortfolioLinkMutation object of the builder.
func (plc *PortfolioLinkCreate) Mutation() *PortfolioLinkMutation {
	return plc.mutation
}

// Save creates the PortfolioLink in the database.
func (plc *PortfolioLinkCreate) Save(ctx context.Context) (*PortfolioLink, error) {
	var (
		err  error
		node *PortfolioLink
	)
	plc.defaults()
	if len(plc.hooks) == 0 {
		if err = plc.check(); err != nil {
			return nil, err
		}
		node, err = plc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*PortfolioLinkMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = plc.check(); err != nil {
				return nil, err
			}
			plc.mutation = mutation
			if node, err = plc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(plc.hooks) - 1; i >= 0; i-- {
			if plc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = plc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, plc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (plc *PortfolioLinkCreate) SaveX(ctx context.Context) *PortfolioLink {
	v, err := plc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plc *PortfolioLinkCreate) Exec(ctx context.Context) error {
	_, err := plc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plc *PortfolioLinkCreate) ExecX(ctx context.Context) {
	if err := plc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (plc *PortfolioLinkCreate) defaults() {
	if _, ok := plc.mutation.UUID(); !ok {
		v := portfoliolink.DefaultUUID()
		plc.mutation.SetUUID(v)
	}
	if _, ok := plc.mutation.CreatedAt(); !ok {
		v := portfoliolink.DefaultCreatedAt()
		plc.mutation.SetCreatedAt(v)
	}
	if _, ok := plc.mutation.UpdatedAt(); !ok {
		v := portfoliolink.DefaultUpdatedAt()
		plc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (plc *PortfolioLinkCreate) check() error {
	if _, ok := plc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "uuid"`)}
	}
	if _, ok := plc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "created_at"`)}
	}
	if _, ok := plc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "updated_at"`)}
	}
	if _, ok := plc.mutation.URL(); !ok {
		return &ValidationError{Name: "url", err: errors.New(`ent: missing required field "url"`)}
	}
	if _, ok := plc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	return nil
}

func (plc *PortfolioLinkCreate) sqlSave(ctx context.Context) (*PortfolioLink, error) {
	_node, _spec := plc.createSpec()
	if err := sqlgraph.CreateNode(ctx, plc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (plc *PortfolioLinkCreate) createSpec() (*PortfolioLink, *sqlgraph.CreateSpec) {
	var (
		_node = &PortfolioLink{config: plc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: portfoliolink.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: portfoliolink.FieldID,
			},
		}
	)
	if id, ok := plc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := plc.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: portfoliolink.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := plc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: portfoliolink.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := plc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: portfoliolink.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := plc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: portfoliolink.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := plc.mutation.URL(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: portfoliolink.FieldURL,
		})
		_node.URL = value
	}
	if value, ok := plc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: portfoliolink.FieldName,
		})
		_node.Name = value
	}
	if nodes := plc.mutation.ApplicantIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   portfoliolink.ApplicantTable,
			Columns: []string{portfoliolink.ApplicantColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: applicant.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ApplicantID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PortfolioLinkCreateBulk is the builder for creating many PortfolioLink entities in bulk.
type PortfolioLinkCreateBulk struct {
	config
	builders []*PortfolioLinkCreate
}

// Save creates the PortfolioLink entities in the database.
func (plcb *PortfolioLinkCreateBulk) Save(ctx context.Context) ([]*PortfolioLink, error) {
	specs := make([]*sqlgraph.CreateSpec, len(plcb.builders))
	nodes := make([]*PortfolioLink, len(plcb.builders))
	mutators := make([]Mutator, len(plcb.builders))
	for i := range plcb.builders {
		func(i int, root context.Context) {
			builder := plcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PortfolioLinkMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, plcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, plcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, plcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (plcb *PortfolioLinkCreateBulk) SaveX(ctx context.Context) []*PortfolioLink {
	v, err := plcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (plcb *PortfolioLinkCreateBulk) Exec(ctx context.Context) error {
	_, err := plcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (plcb *PortfolioLinkCreateBulk) ExecX(ctx context.Context) {
	if err := plcb.Exec(ctx); err != nil {
		panic(err)
	}
}
