// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/predicate"
	"github.com/10hourlabs/tentn/ent/slackappinstall"
	"github.com/10hourlabs/tentn/ent/slackappuser"
	"github.com/google/uuid"
)

// SlackAppUserUpdate is the builder for updating SlackAppUser entities.
type SlackAppUserUpdate struct {
	config
	hooks    []Hook
	mutation *SlackAppUserMutation
}

// Where appends a list predicates to the SlackAppUserUpdate builder.
func (sauu *SlackAppUserUpdate) Where(ps ...predicate.SlackAppUser) *SlackAppUserUpdate {
	sauu.mutation.Where(ps...)
	return sauu
}

// SetUpdatedAt sets the "updated_at" field.
func (sauu *SlackAppUserUpdate) SetUpdatedAt(t time.Time) *SlackAppUserUpdate {
	sauu.mutation.SetUpdatedAt(t)
	return sauu
}

// SetDeletedAt sets the "deleted_at" field.
func (sauu *SlackAppUserUpdate) SetDeletedAt(t time.Time) *SlackAppUserUpdate {
	sauu.mutation.SetDeletedAt(t)
	return sauu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sauu *SlackAppUserUpdate) SetNillableDeletedAt(t *time.Time) *SlackAppUserUpdate {
	if t != nil {
		sauu.SetDeletedAt(*t)
	}
	return sauu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sauu *SlackAppUserUpdate) ClearDeletedAt() *SlackAppUserUpdate {
	sauu.mutation.ClearDeletedAt()
	return sauu
}

// SetSlackAppInstallID sets the "slack_app_install_id" field.
func (sauu *SlackAppUserUpdate) SetSlackAppInstallID(u uuid.UUID) *SlackAppUserUpdate {
	sauu.mutation.SetSlackAppInstallID(u)
	return sauu
}

// SetNillableSlackAppInstallID sets the "slack_app_install_id" field if the given value is not nil.
func (sauu *SlackAppUserUpdate) SetNillableSlackAppInstallID(u *uuid.UUID) *SlackAppUserUpdate {
	if u != nil {
		sauu.SetSlackAppInstallID(*u)
	}
	return sauu
}

// ClearSlackAppInstallID clears the value of the "slack_app_install_id" field.
func (sauu *SlackAppUserUpdate) ClearSlackAppInstallID() *SlackAppUserUpdate {
	sauu.mutation.ClearSlackAppInstallID()
	return sauu
}

// SetFullName sets the "full_name" field.
func (sauu *SlackAppUserUpdate) SetFullName(s string) *SlackAppUserUpdate {
	sauu.mutation.SetFullName(s)
	return sauu
}

// SetTitle sets the "title" field.
func (sauu *SlackAppUserUpdate) SetTitle(s string) *SlackAppUserUpdate {
	sauu.mutation.SetTitle(s)
	return sauu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (sauu *SlackAppUserUpdate) SetNillableTitle(s *string) *SlackAppUserUpdate {
	if s != nil {
		sauu.SetTitle(*s)
	}
	return sauu
}

// ClearTitle clears the value of the "title" field.
func (sauu *SlackAppUserUpdate) ClearTitle() *SlackAppUserUpdate {
	sauu.mutation.ClearTitle()
	return sauu
}

// SetEmail sets the "email" field.
func (sauu *SlackAppUserUpdate) SetEmail(s string) *SlackAppUserUpdate {
	sauu.mutation.SetEmail(s)
	return sauu
}

// SetPhotoURL sets the "photo_url" field.
func (sauu *SlackAppUserUpdate) SetPhotoURL(s string) *SlackAppUserUpdate {
	sauu.mutation.SetPhotoURL(s)
	return sauu
}

// SetSlackUserID sets the "slack_user_id" field.
func (sauu *SlackAppUserUpdate) SetSlackUserID(s string) *SlackAppUserUpdate {
	sauu.mutation.SetSlackUserID(s)
	return sauu
}

// SetSlackTeamID sets the "slack_team_id" field.
func (sauu *SlackAppUserUpdate) SetSlackTeamID(s string) *SlackAppUserUpdate {
	sauu.mutation.SetSlackTeamID(s)
	return sauu
}

// SetTimezone sets the "timezone" field.
func (sauu *SlackAppUserUpdate) SetTimezone(s string) *SlackAppUserUpdate {
	sauu.mutation.SetTimezone(s)
	return sauu
}

// SetTimezoneLabel sets the "timezone_label" field.
func (sauu *SlackAppUserUpdate) SetTimezoneLabel(s string) *SlackAppUserUpdate {
	sauu.mutation.SetTimezoneLabel(s)
	return sauu
}

// SetLocale sets the "locale" field.
func (sauu *SlackAppUserUpdate) SetLocale(s string) *SlackAppUserUpdate {
	sauu.mutation.SetLocale(s)
	return sauu
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (sauu *SlackAppUserUpdate) SetNillableLocale(s *string) *SlackAppUserUpdate {
	if s != nil {
		sauu.SetLocale(*s)
	}
	return sauu
}

// SetIsBotUser sets the "is_bot_user" field.
func (sauu *SlackAppUserUpdate) SetIsBotUser(b bool) *SlackAppUserUpdate {
	sauu.mutation.SetIsBotUser(b)
	return sauu
}

// SetSlackAppInstall sets the "slack_app_install" edge to the SlackAppInstall entity.
func (sauu *SlackAppUserUpdate) SetSlackAppInstall(s *SlackAppInstall) *SlackAppUserUpdate {
	return sauu.SetSlackAppInstallID(s.ID)
}

// Mutation returns the SlackAppUserMutation object of the builder.
func (sauu *SlackAppUserUpdate) Mutation() *SlackAppUserMutation {
	return sauu.mutation
}

// ClearSlackAppInstall clears the "slack_app_install" edge to the SlackAppInstall entity.
func (sauu *SlackAppUserUpdate) ClearSlackAppInstall() *SlackAppUserUpdate {
	sauu.mutation.ClearSlackAppInstall()
	return sauu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (sauu *SlackAppUserUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	sauu.defaults()
	if len(sauu.hooks) == 0 {
		affected, err = sauu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SlackAppUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sauu.mutation = mutation
			affected, err = sauu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(sauu.hooks) - 1; i >= 0; i-- {
			if sauu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sauu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sauu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (sauu *SlackAppUserUpdate) SaveX(ctx context.Context) int {
	affected, err := sauu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (sauu *SlackAppUserUpdate) Exec(ctx context.Context) error {
	_, err := sauu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sauu *SlackAppUserUpdate) ExecX(ctx context.Context) {
	if err := sauu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sauu *SlackAppUserUpdate) defaults() {
	if _, ok := sauu.mutation.UpdatedAt(); !ok {
		v := slackappuser.UpdateDefaultUpdatedAt()
		sauu.mutation.SetUpdatedAt(v)
	}
}

func (sauu *SlackAppUserUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   slackappuser.Table,
			Columns: slackappuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: slackappuser.FieldID,
			},
		},
	}
	if ps := sauu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sauu.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slackappuser.FieldUpdatedAt,
		})
	}
	if value, ok := sauu.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slackappuser.FieldDeletedAt,
		})
	}
	if sauu.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: slackappuser.FieldDeletedAt,
		})
	}
	if value, ok := sauu.mutation.FullName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldFullName,
		})
	}
	if value, ok := sauu.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldTitle,
		})
	}
	if sauu.mutation.TitleCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: slackappuser.FieldTitle,
		})
	}
	if value, ok := sauu.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldEmail,
		})
	}
	if value, ok := sauu.mutation.PhotoURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldPhotoURL,
		})
	}
	if value, ok := sauu.mutation.SlackUserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldSlackUserID,
		})
	}
	if value, ok := sauu.mutation.SlackTeamID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldSlackTeamID,
		})
	}
	if value, ok := sauu.mutation.Timezone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldTimezone,
		})
	}
	if value, ok := sauu.mutation.TimezoneLabel(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldTimezoneLabel,
		})
	}
	if value, ok := sauu.mutation.Locale(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldLocale,
		})
	}
	if value, ok := sauu.mutation.IsBotUser(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: slackappuser.FieldIsBotUser,
		})
	}
	if sauu.mutation.SlackAppInstallCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slackappuser.SlackAppInstallTable,
			Columns: []string{slackappuser.SlackAppInstallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: slackappinstall.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sauu.mutation.SlackAppInstallIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slackappuser.SlackAppInstallTable,
			Columns: []string{slackappuser.SlackAppInstallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: slackappinstall.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, sauu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{slackappuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// SlackAppUserUpdateOne is the builder for updating a single SlackAppUser entity.
type SlackAppUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SlackAppUserMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (sauuo *SlackAppUserUpdateOne) SetUpdatedAt(t time.Time) *SlackAppUserUpdateOne {
	sauuo.mutation.SetUpdatedAt(t)
	return sauuo
}

// SetDeletedAt sets the "deleted_at" field.
func (sauuo *SlackAppUserUpdateOne) SetDeletedAt(t time.Time) *SlackAppUserUpdateOne {
	sauuo.mutation.SetDeletedAt(t)
	return sauuo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (sauuo *SlackAppUserUpdateOne) SetNillableDeletedAt(t *time.Time) *SlackAppUserUpdateOne {
	if t != nil {
		sauuo.SetDeletedAt(*t)
	}
	return sauuo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (sauuo *SlackAppUserUpdateOne) ClearDeletedAt() *SlackAppUserUpdateOne {
	sauuo.mutation.ClearDeletedAt()
	return sauuo
}

// SetSlackAppInstallID sets the "slack_app_install_id" field.
func (sauuo *SlackAppUserUpdateOne) SetSlackAppInstallID(u uuid.UUID) *SlackAppUserUpdateOne {
	sauuo.mutation.SetSlackAppInstallID(u)
	return sauuo
}

// SetNillableSlackAppInstallID sets the "slack_app_install_id" field if the given value is not nil.
func (sauuo *SlackAppUserUpdateOne) SetNillableSlackAppInstallID(u *uuid.UUID) *SlackAppUserUpdateOne {
	if u != nil {
		sauuo.SetSlackAppInstallID(*u)
	}
	return sauuo
}

// ClearSlackAppInstallID clears the value of the "slack_app_install_id" field.
func (sauuo *SlackAppUserUpdateOne) ClearSlackAppInstallID() *SlackAppUserUpdateOne {
	sauuo.mutation.ClearSlackAppInstallID()
	return sauuo
}

// SetFullName sets the "full_name" field.
func (sauuo *SlackAppUserUpdateOne) SetFullName(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetFullName(s)
	return sauuo
}

// SetTitle sets the "title" field.
func (sauuo *SlackAppUserUpdateOne) SetTitle(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetTitle(s)
	return sauuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (sauuo *SlackAppUserUpdateOne) SetNillableTitle(s *string) *SlackAppUserUpdateOne {
	if s != nil {
		sauuo.SetTitle(*s)
	}
	return sauuo
}

// ClearTitle clears the value of the "title" field.
func (sauuo *SlackAppUserUpdateOne) ClearTitle() *SlackAppUserUpdateOne {
	sauuo.mutation.ClearTitle()
	return sauuo
}

// SetEmail sets the "email" field.
func (sauuo *SlackAppUserUpdateOne) SetEmail(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetEmail(s)
	return sauuo
}

// SetPhotoURL sets the "photo_url" field.
func (sauuo *SlackAppUserUpdateOne) SetPhotoURL(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetPhotoURL(s)
	return sauuo
}

// SetSlackUserID sets the "slack_user_id" field.
func (sauuo *SlackAppUserUpdateOne) SetSlackUserID(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetSlackUserID(s)
	return sauuo
}

// SetSlackTeamID sets the "slack_team_id" field.
func (sauuo *SlackAppUserUpdateOne) SetSlackTeamID(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetSlackTeamID(s)
	return sauuo
}

// SetTimezone sets the "timezone" field.
func (sauuo *SlackAppUserUpdateOne) SetTimezone(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetTimezone(s)
	return sauuo
}

// SetTimezoneLabel sets the "timezone_label" field.
func (sauuo *SlackAppUserUpdateOne) SetTimezoneLabel(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetTimezoneLabel(s)
	return sauuo
}

// SetLocale sets the "locale" field.
func (sauuo *SlackAppUserUpdateOne) SetLocale(s string) *SlackAppUserUpdateOne {
	sauuo.mutation.SetLocale(s)
	return sauuo
}

// SetNillableLocale sets the "locale" field if the given value is not nil.
func (sauuo *SlackAppUserUpdateOne) SetNillableLocale(s *string) *SlackAppUserUpdateOne {
	if s != nil {
		sauuo.SetLocale(*s)
	}
	return sauuo
}

// SetIsBotUser sets the "is_bot_user" field.
func (sauuo *SlackAppUserUpdateOne) SetIsBotUser(b bool) *SlackAppUserUpdateOne {
	sauuo.mutation.SetIsBotUser(b)
	return sauuo
}

// SetSlackAppInstall sets the "slack_app_install" edge to the SlackAppInstall entity.
func (sauuo *SlackAppUserUpdateOne) SetSlackAppInstall(s *SlackAppInstall) *SlackAppUserUpdateOne {
	return sauuo.SetSlackAppInstallID(s.ID)
}

// Mutation returns the SlackAppUserMutation object of the builder.
func (sauuo *SlackAppUserUpdateOne) Mutation() *SlackAppUserMutation {
	return sauuo.mutation
}

// ClearSlackAppInstall clears the "slack_app_install" edge to the SlackAppInstall entity.
func (sauuo *SlackAppUserUpdateOne) ClearSlackAppInstall() *SlackAppUserUpdateOne {
	sauuo.mutation.ClearSlackAppInstall()
	return sauuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (sauuo *SlackAppUserUpdateOne) Select(field string, fields ...string) *SlackAppUserUpdateOne {
	sauuo.fields = append([]string{field}, fields...)
	return sauuo
}

// Save executes the query and returns the updated SlackAppUser entity.
func (sauuo *SlackAppUserUpdateOne) Save(ctx context.Context) (*SlackAppUser, error) {
	var (
		err  error
		node *SlackAppUser
	)
	sauuo.defaults()
	if len(sauuo.hooks) == 0 {
		node, err = sauuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SlackAppUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			sauuo.mutation = mutation
			node, err = sauuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(sauuo.hooks) - 1; i >= 0; i-- {
			if sauuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sauuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, sauuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (sauuo *SlackAppUserUpdateOne) SaveX(ctx context.Context) *SlackAppUser {
	node, err := sauuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (sauuo *SlackAppUserUpdateOne) Exec(ctx context.Context) error {
	_, err := sauuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sauuo *SlackAppUserUpdateOne) ExecX(ctx context.Context) {
	if err := sauuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (sauuo *SlackAppUserUpdateOne) defaults() {
	if _, ok := sauuo.mutation.UpdatedAt(); !ok {
		v := slackappuser.UpdateDefaultUpdatedAt()
		sauuo.mutation.SetUpdatedAt(v)
	}
}

func (sauuo *SlackAppUserUpdateOne) sqlSave(ctx context.Context) (_node *SlackAppUser, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   slackappuser.Table,
			Columns: slackappuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: slackappuser.FieldID,
			},
		},
	}
	id, ok := sauuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SlackAppUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := sauuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, slackappuser.FieldID)
		for _, f := range fields {
			if !slackappuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != slackappuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := sauuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := sauuo.mutation.UpdatedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slackappuser.FieldUpdatedAt,
		})
	}
	if value, ok := sauuo.mutation.DeletedAt(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slackappuser.FieldDeletedAt,
		})
	}
	if sauuo.mutation.DeletedAtCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Column: slackappuser.FieldDeletedAt,
		})
	}
	if value, ok := sauuo.mutation.FullName(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldFullName,
		})
	}
	if value, ok := sauuo.mutation.Title(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldTitle,
		})
	}
	if sauuo.mutation.TitleCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Column: slackappuser.FieldTitle,
		})
	}
	if value, ok := sauuo.mutation.Email(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldEmail,
		})
	}
	if value, ok := sauuo.mutation.PhotoURL(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldPhotoURL,
		})
	}
	if value, ok := sauuo.mutation.SlackUserID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldSlackUserID,
		})
	}
	if value, ok := sauuo.mutation.SlackTeamID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldSlackTeamID,
		})
	}
	if value, ok := sauuo.mutation.Timezone(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldTimezone,
		})
	}
	if value, ok := sauuo.mutation.TimezoneLabel(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldTimezoneLabel,
		})
	}
	if value, ok := sauuo.mutation.Locale(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappuser.FieldLocale,
		})
	}
	if value, ok := sauuo.mutation.IsBotUser(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: slackappuser.FieldIsBotUser,
		})
	}
	if sauuo.mutation.SlackAppInstallCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slackappuser.SlackAppInstallTable,
			Columns: []string{slackappuser.SlackAppInstallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: slackappinstall.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := sauuo.mutation.SlackAppInstallIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slackappuser.SlackAppInstallTable,
			Columns: []string{slackappuser.SlackAppInstallColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: slackappinstall.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SlackAppUser{config: sauuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, sauuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{slackappuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
