// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/schema/billing"
	"github.com/10hourlabs/tentn/ent/slackappinstall"
	"github.com/10hourlabs/tentn/ent/slackappuser"
	"github.com/10hourlabs/tentn/ent/user"
	"github.com/google/uuid"
)

// SlackAppInstallCreate is the builder for creating a SlackAppInstall entity.
type SlackAppInstallCreate struct {
	config
	mutation *SlackAppInstallMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (saic *SlackAppInstallCreate) SetCreatedAt(t time.Time) *SlackAppInstallCreate {
	saic.mutation.SetCreatedAt(t)
	return saic
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillableCreatedAt(t *time.Time) *SlackAppInstallCreate {
	if t != nil {
		saic.SetCreatedAt(*t)
	}
	return saic
}

// SetUpdatedAt sets the "updated_at" field.
func (saic *SlackAppInstallCreate) SetUpdatedAt(t time.Time) *SlackAppInstallCreate {
	saic.mutation.SetUpdatedAt(t)
	return saic
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillableUpdatedAt(t *time.Time) *SlackAppInstallCreate {
	if t != nil {
		saic.SetUpdatedAt(*t)
	}
	return saic
}

// SetDeletedAt sets the "deleted_at" field.
func (saic *SlackAppInstallCreate) SetDeletedAt(t time.Time) *SlackAppInstallCreate {
	saic.mutation.SetDeletedAt(t)
	return saic
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillableDeletedAt(t *time.Time) *SlackAppInstallCreate {
	if t != nil {
		saic.SetDeletedAt(*t)
	}
	return saic
}

// SetUserID sets the "user_id" field.
func (saic *SlackAppInstallCreate) SetUserID(u uuid.UUID) *SlackAppInstallCreate {
	saic.mutation.SetUserID(u)
	return saic
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillableUserID(u *uuid.UUID) *SlackAppInstallCreate {
	if u != nil {
		saic.SetUserID(*u)
	}
	return saic
}

// SetTeamID sets the "team_id" field.
func (saic *SlackAppInstallCreate) SetTeamID(s string) *SlackAppInstallCreate {
	saic.mutation.SetTeamID(s)
	return saic
}

// SetTeamName sets the "team_name" field.
func (saic *SlackAppInstallCreate) SetTeamName(s string) *SlackAppInstallCreate {
	saic.mutation.SetTeamName(s)
	return saic
}

// SetAuthedUserID sets the "authed_user_id" field.
func (saic *SlackAppInstallCreate) SetAuthedUserID(s string) *SlackAppInstallCreate {
	saic.mutation.SetAuthedUserID(s)
	return saic
}

// SetAuthedUserEmail sets the "authed_user_email" field.
func (saic *SlackAppInstallCreate) SetAuthedUserEmail(s string) *SlackAppInstallCreate {
	saic.mutation.SetAuthedUserEmail(s)
	return saic
}

// SetAuthedUserTitle sets the "authed_user_title" field.
func (saic *SlackAppInstallCreate) SetAuthedUserTitle(s string) *SlackAppInstallCreate {
	saic.mutation.SetAuthedUserTitle(s)
	return saic
}

// SetNillableAuthedUserTitle sets the "authed_user_title" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillableAuthedUserTitle(s *string) *SlackAppInstallCreate {
	if s != nil {
		saic.SetAuthedUserTitle(*s)
	}
	return saic
}

// SetAuthedUserPhone sets the "authed_user_phone" field.
func (saic *SlackAppInstallCreate) SetAuthedUserPhone(s string) *SlackAppInstallCreate {
	saic.mutation.SetAuthedUserPhone(s)
	return saic
}

// SetNillableAuthedUserPhone sets the "authed_user_phone" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillableAuthedUserPhone(s *string) *SlackAppInstallCreate {
	if s != nil {
		saic.SetAuthedUserPhone(*s)
	}
	return saic
}

// SetAppID sets the "app_id" field.
func (saic *SlackAppInstallCreate) SetAppID(s string) *SlackAppInstallCreate {
	saic.mutation.SetAppID(s)
	return saic
}

// SetBotUserID sets the "bot_user_id" field.
func (saic *SlackAppInstallCreate) SetBotUserID(s string) *SlackAppInstallCreate {
	saic.mutation.SetBotUserID(s)
	return saic
}

// SetAccessToken sets the "access_token" field.
func (saic *SlackAppInstallCreate) SetAccessToken(s string) *SlackAppInstallCreate {
	saic.mutation.SetAccessToken(s)
	return saic
}

// SetTokenType sets the "token_type" field.
func (saic *SlackAppInstallCreate) SetTokenType(s string) *SlackAppInstallCreate {
	saic.mutation.SetTokenType(s)
	return saic
}

// SetScope sets the "scope" field.
func (saic *SlackAppInstallCreate) SetScope(s string) *SlackAppInstallCreate {
	saic.mutation.SetScope(s)
	return saic
}

// SetIsEnterpriseInstall sets the "is_enterprise_install" field.
func (saic *SlackAppInstallCreate) SetIsEnterpriseInstall(b bool) *SlackAppInstallCreate {
	saic.mutation.SetIsEnterpriseInstall(b)
	return saic
}

// SetPaymentPlan sets the "payment_plan" field.
func (saic *SlackAppInstallCreate) SetPaymentPlan(bp billing.PaymentPlan) *SlackAppInstallCreate {
	saic.mutation.SetPaymentPlan(bp)
	return saic
}

// SetNillablePaymentPlan sets the "payment_plan" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillablePaymentPlan(bp *billing.PaymentPlan) *SlackAppInstallCreate {
	if bp != nil {
		saic.SetPaymentPlan(*bp)
	}
	return saic
}

// SetID sets the "id" field.
func (saic *SlackAppInstallCreate) SetID(u uuid.UUID) *SlackAppInstallCreate {
	saic.mutation.SetID(u)
	return saic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (saic *SlackAppInstallCreate) SetNillableID(u *uuid.UUID) *SlackAppInstallCreate {
	if u != nil {
		saic.SetID(*u)
	}
	return saic
}

// SetUser sets the "user" edge to the User entity.
func (saic *SlackAppInstallCreate) SetUser(u *User) *SlackAppInstallCreate {
	return saic.SetUserID(u.ID)
}

// AddSlackAppUserIDs adds the "slack_app_users" edge to the SlackAppUser entity by IDs.
func (saic *SlackAppInstallCreate) AddSlackAppUserIDs(ids ...uuid.UUID) *SlackAppInstallCreate {
	saic.mutation.AddSlackAppUserIDs(ids...)
	return saic
}

// AddSlackAppUsers adds the "slack_app_users" edges to the SlackAppUser entity.
func (saic *SlackAppInstallCreate) AddSlackAppUsers(s ...*SlackAppUser) *SlackAppInstallCreate {
	ids := make([]uuid.UUID, len(s))
	for i := range s {
		ids[i] = s[i].ID
	}
	return saic.AddSlackAppUserIDs(ids...)
}

// Mutation returns the SlackAppInstallMutation object of the builder.
func (saic *SlackAppInstallCreate) Mutation() *SlackAppInstallMutation {
	return saic.mutation
}

// Save creates the SlackAppInstall in the database.
func (saic *SlackAppInstallCreate) Save(ctx context.Context) (*SlackAppInstall, error) {
	var (
		err  error
		node *SlackAppInstall
	)
	saic.defaults()
	if len(saic.hooks) == 0 {
		if err = saic.check(); err != nil {
			return nil, err
		}
		node, err = saic.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SlackAppInstallMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = saic.check(); err != nil {
				return nil, err
			}
			saic.mutation = mutation
			if node, err = saic.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(saic.hooks) - 1; i >= 0; i-- {
			if saic.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = saic.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, saic.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (saic *SlackAppInstallCreate) SaveX(ctx context.Context) *SlackAppInstall {
	v, err := saic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (saic *SlackAppInstallCreate) Exec(ctx context.Context) error {
	_, err := saic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (saic *SlackAppInstallCreate) ExecX(ctx context.Context) {
	if err := saic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (saic *SlackAppInstallCreate) defaults() {
	if _, ok := saic.mutation.CreatedAt(); !ok {
		v := slackappinstall.DefaultCreatedAt()
		saic.mutation.SetCreatedAt(v)
	}
	if _, ok := saic.mutation.UpdatedAt(); !ok {
		v := slackappinstall.DefaultUpdatedAt()
		saic.mutation.SetUpdatedAt(v)
	}
	if _, ok := saic.mutation.PaymentPlan(); !ok {
		v := slackappinstall.DefaultPaymentPlan
		saic.mutation.SetPaymentPlan(v)
	}
	if _, ok := saic.mutation.ID(); !ok {
		v := slackappinstall.DefaultID()
		saic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (saic *SlackAppInstallCreate) check() error {
	if _, ok := saic.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SlackAppInstall.created_at"`)}
	}
	if _, ok := saic.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SlackAppInstall.updated_at"`)}
	}
	if _, ok := saic.mutation.TeamID(); !ok {
		return &ValidationError{Name: "team_id", err: errors.New(`ent: missing required field "SlackAppInstall.team_id"`)}
	}
	if _, ok := saic.mutation.TeamName(); !ok {
		return &ValidationError{Name: "team_name", err: errors.New(`ent: missing required field "SlackAppInstall.team_name"`)}
	}
	if _, ok := saic.mutation.AuthedUserID(); !ok {
		return &ValidationError{Name: "authed_user_id", err: errors.New(`ent: missing required field "SlackAppInstall.authed_user_id"`)}
	}
	if _, ok := saic.mutation.AuthedUserEmail(); !ok {
		return &ValidationError{Name: "authed_user_email", err: errors.New(`ent: missing required field "SlackAppInstall.authed_user_email"`)}
	}
	if _, ok := saic.mutation.AppID(); !ok {
		return &ValidationError{Name: "app_id", err: errors.New(`ent: missing required field "SlackAppInstall.app_id"`)}
	}
	if _, ok := saic.mutation.BotUserID(); !ok {
		return &ValidationError{Name: "bot_user_id", err: errors.New(`ent: missing required field "SlackAppInstall.bot_user_id"`)}
	}
	if _, ok := saic.mutation.AccessToken(); !ok {
		return &ValidationError{Name: "access_token", err: errors.New(`ent: missing required field "SlackAppInstall.access_token"`)}
	}
	if _, ok := saic.mutation.TokenType(); !ok {
		return &ValidationError{Name: "token_type", err: errors.New(`ent: missing required field "SlackAppInstall.token_type"`)}
	}
	if _, ok := saic.mutation.Scope(); !ok {
		return &ValidationError{Name: "scope", err: errors.New(`ent: missing required field "SlackAppInstall.scope"`)}
	}
	if _, ok := saic.mutation.IsEnterpriseInstall(); !ok {
		return &ValidationError{Name: "is_enterprise_install", err: errors.New(`ent: missing required field "SlackAppInstall.is_enterprise_install"`)}
	}
	if _, ok := saic.mutation.PaymentPlan(); !ok {
		return &ValidationError{Name: "payment_plan", err: errors.New(`ent: missing required field "SlackAppInstall.payment_plan"`)}
	}
	if v, ok := saic.mutation.PaymentPlan(); ok {
		if err := slackappinstall.PaymentPlanValidator(v); err != nil {
			return &ValidationError{Name: "payment_plan", err: fmt.Errorf(`ent: validator failed for field "SlackAppInstall.payment_plan": %w`, err)}
		}
	}
	return nil
}

func (saic *SlackAppInstallCreate) sqlSave(ctx context.Context) (*SlackAppInstall, error) {
	_node, _spec := saic.createSpec()
	if err := sqlgraph.CreateNode(ctx, saic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	return _node, nil
}

func (saic *SlackAppInstallCreate) createSpec() (*SlackAppInstall, *sqlgraph.CreateSpec) {
	var (
		_node = &SlackAppInstall{config: saic.config}
		_spec = &sqlgraph.CreateSpec{
			Table: slackappinstall.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: slackappinstall.FieldID,
			},
		}
	)
	if id, ok := saic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := saic.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slackappinstall.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := saic.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slackappinstall.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := saic.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: slackappinstall.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := saic.mutation.TeamID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldTeamID,
		})
		_node.TeamID = value
	}
	if value, ok := saic.mutation.TeamName(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldTeamName,
		})
		_node.TeamName = value
	}
	if value, ok := saic.mutation.AuthedUserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldAuthedUserID,
		})
		_node.AuthedUserID = value
	}
	if value, ok := saic.mutation.AuthedUserEmail(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldAuthedUserEmail,
		})
		_node.AuthedUserEmail = value
	}
	if value, ok := saic.mutation.AuthedUserTitle(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldAuthedUserTitle,
		})
		_node.AuthedUserTitle = value
	}
	if value, ok := saic.mutation.AuthedUserPhone(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldAuthedUserPhone,
		})
		_node.AuthedUserPhone = value
	}
	if value, ok := saic.mutation.AppID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldAppID,
		})
		_node.AppID = value
	}
	if value, ok := saic.mutation.BotUserID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldBotUserID,
		})
		_node.BotUserID = value
	}
	if value, ok := saic.mutation.AccessToken(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldAccessToken,
		})
		_node.AccessToken = value
	}
	if value, ok := saic.mutation.TokenType(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldTokenType,
		})
		_node.TokenType = value
	}
	if value, ok := saic.mutation.Scope(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: slackappinstall.FieldScope,
		})
		_node.Scope = value
	}
	if value, ok := saic.mutation.IsEnterpriseInstall(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeBool,
			Value:  value,
			Column: slackappinstall.FieldIsEnterpriseInstall,
		})
		_node.IsEnterpriseInstall = value
	}
	if value, ok := saic.mutation.PaymentPlan(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeEnum,
			Value:  value,
			Column: slackappinstall.FieldPaymentPlan,
		})
		_node.PaymentPlan = value
	}
	if nodes := saic.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   slackappinstall.UserTable,
			Columns: []string{slackappinstall.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := saic.mutation.SlackAppUsersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   slackappinstall.SlackAppUsersTable,
			Columns: []string{slackappinstall.SlackAppUsersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeUUID,
					Column: slackappuser.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SlackAppInstallCreateBulk is the builder for creating many SlackAppInstall entities in bulk.
type SlackAppInstallCreateBulk struct {
	config
	builders []*SlackAppInstallCreate
}

// Save creates the SlackAppInstall entities in the database.
func (saicb *SlackAppInstallCreateBulk) Save(ctx context.Context) ([]*SlackAppInstall, error) {
	specs := make([]*sqlgraph.CreateSpec, len(saicb.builders))
	nodes := make([]*SlackAppInstall, len(saicb.builders))
	mutators := make([]Mutator, len(saicb.builders))
	for i := range saicb.builders {
		func(i int, root context.Context) {
			builder := saicb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SlackAppInstallMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, saicb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, saicb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, saicb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (saicb *SlackAppInstallCreateBulk) SaveX(ctx context.Context) []*SlackAppInstall {
	v, err := saicb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (saicb *SlackAppInstallCreateBulk) Exec(ctx context.Context) error {
	_, err := saicb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (saicb *SlackAppInstallCreateBulk) ExecX(ctx context.Context) {
	if err := saicb.Exec(ctx); err != nil {
		panic(err)
	}
}
