// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/talentcollection"
	"github.com/10hourlabs/tentn/ent/user"
	"github.com/google/uuid"
)

// TalentCollectionCreate is the builder for creating a TalentCollection entity.
type TalentCollectionCreate struct {
	config
	mutation *TalentCollectionMutation
	hooks    []Hook
}

// SetUUID sets the "uuid" field.
func (tcc *TalentCollectionCreate) SetUUID(u uuid.UUID) *TalentCollectionCreate {
	tcc.mutation.SetUUID(u)
	return tcc
}

// SetNillableUUID sets the "uuid" field if the given value is not nil.
func (tcc *TalentCollectionCreate) SetNillableUUID(u *uuid.UUID) *TalentCollectionCreate {
	if u != nil {
		tcc.SetUUID(*u)
	}
	return tcc
}

// SetCreatedAt sets the "created_at" field.
func (tcc *TalentCollectionCreate) SetCreatedAt(t time.Time) *TalentCollectionCreate {
	tcc.mutation.SetCreatedAt(t)
	return tcc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (tcc *TalentCollectionCreate) SetNillableCreatedAt(t *time.Time) *TalentCollectionCreate {
	if t != nil {
		tcc.SetCreatedAt(*t)
	}
	return tcc
}

// SetUpdatedAt sets the "updated_at" field.
func (tcc *TalentCollectionCreate) SetUpdatedAt(t time.Time) *TalentCollectionCreate {
	tcc.mutation.SetUpdatedAt(t)
	return tcc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (tcc *TalentCollectionCreate) SetNillableUpdatedAt(t *time.Time) *TalentCollectionCreate {
	if t != nil {
		tcc.SetUpdatedAt(*t)
	}
	return tcc
}

// SetDeletedAt sets the "deleted_at" field.
func (tcc *TalentCollectionCreate) SetDeletedAt(t time.Time) *TalentCollectionCreate {
	tcc.mutation.SetDeletedAt(t)
	return tcc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (tcc *TalentCollectionCreate) SetNillableDeletedAt(t *time.Time) *TalentCollectionCreate {
	if t != nil {
		tcc.SetDeletedAt(*t)
	}
	return tcc
}

// SetUserID sets the "user_id" field.
func (tcc *TalentCollectionCreate) SetUserID(i int) *TalentCollectionCreate {
	tcc.mutation.SetUserID(i)
	return tcc
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (tcc *TalentCollectionCreate) SetNillableUserID(i *int) *TalentCollectionCreate {
	if i != nil {
		tcc.SetUserID(*i)
	}
	return tcc
}

// SetName sets the "name" field.
func (tcc *TalentCollectionCreate) SetName(s string) *TalentCollectionCreate {
	tcc.mutation.SetName(s)
	return tcc
}

// SetTalentUuids sets the "talent_uuids" field.
func (tcc *TalentCollectionCreate) SetTalentUuids(s []string) *TalentCollectionCreate {
	tcc.mutation.SetTalentUuids(s)
	return tcc
}

// SetID sets the "id" field.
func (tcc *TalentCollectionCreate) SetID(i int) *TalentCollectionCreate {
	tcc.mutation.SetID(i)
	return tcc
}

// SetUser sets the "user" edge to the User entity.
func (tcc *TalentCollectionCreate) SetUser(u *User) *TalentCollectionCreate {
	return tcc.SetUserID(u.ID)
}

// Mutation returns the TalentCollectionMutation object of the builder.
func (tcc *TalentCollectionCreate) Mutation() *TalentCollectionMutation {
	return tcc.mutation
}

// Save creates the TalentCollection in the database.
func (tcc *TalentCollectionCreate) Save(ctx context.Context) (*TalentCollection, error) {
	var (
		err  error
		node *TalentCollection
	)
	tcc.defaults()
	if len(tcc.hooks) == 0 {
		if err = tcc.check(); err != nil {
			return nil, err
		}
		node, err = tcc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*TalentCollectionMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = tcc.check(); err != nil {
				return nil, err
			}
			tcc.mutation = mutation
			if node, err = tcc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(tcc.hooks) - 1; i >= 0; i-- {
			if tcc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = tcc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, tcc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (tcc *TalentCollectionCreate) SaveX(ctx context.Context) *TalentCollection {
	v, err := tcc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tcc *TalentCollectionCreate) Exec(ctx context.Context) error {
	_, err := tcc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tcc *TalentCollectionCreate) ExecX(ctx context.Context) {
	if err := tcc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tcc *TalentCollectionCreate) defaults() {
	if _, ok := tcc.mutation.UUID(); !ok {
		v := talentcollection.DefaultUUID()
		tcc.mutation.SetUUID(v)
	}
	if _, ok := tcc.mutation.CreatedAt(); !ok {
		v := talentcollection.DefaultCreatedAt()
		tcc.mutation.SetCreatedAt(v)
	}
	if _, ok := tcc.mutation.UpdatedAt(); !ok {
		v := talentcollection.DefaultUpdatedAt()
		tcc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tcc *TalentCollectionCreate) check() error {
	if _, ok := tcc.mutation.UUID(); !ok {
		return &ValidationError{Name: "uuid", err: errors.New(`ent: missing required field "TalentCollection.uuid"`)}
	}
	if _, ok := tcc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "TalentCollection.created_at"`)}
	}
	if _, ok := tcc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "TalentCollection.updated_at"`)}
	}
	if _, ok := tcc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "TalentCollection.name"`)}
	}
	if _, ok := tcc.mutation.TalentUuids(); !ok {
		return &ValidationError{Name: "talent_uuids", err: errors.New(`ent: missing required field "TalentCollection.talent_uuids"`)}
	}
	return nil
}

func (tcc *TalentCollectionCreate) sqlSave(ctx context.Context) (*TalentCollection, error) {
	_node, _spec := tcc.createSpec()
	if err := sqlgraph.CreateNode(ctx, tcc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (tcc *TalentCollectionCreate) createSpec() (*TalentCollection, *sqlgraph.CreateSpec) {
	var (
		_node = &TalentCollection{config: tcc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: talentcollection.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: talentcollection.FieldID,
			},
		}
	)
	if id, ok := tcc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := tcc.mutation.UUID(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeUUID,
			Value:  value,
			Column: talentcollection.FieldUUID,
		})
		_node.UUID = value
	}
	if value, ok := tcc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: talentcollection.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := tcc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: talentcollection.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if value, ok := tcc.mutation.DeletedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: talentcollection.FieldDeletedAt,
		})
		_node.DeletedAt = &value
	}
	if value, ok := tcc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: talentcollection.FieldName,
		})
		_node.Name = value
	}
	if value, ok := tcc.mutation.TalentUuids(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeJSON,
			Value:  value,
			Column: talentcollection.FieldTalentUuids,
		})
		_node.TalentUuids = value
	}
	if nodes := tcc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   talentcollection.UserTable,
			Columns: []string{talentcollection.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// TalentCollectionCreateBulk is the builder for creating many TalentCollection entities in bulk.
type TalentCollectionCreateBulk struct {
	config
	builders []*TalentCollectionCreate
}

// Save creates the TalentCollection entities in the database.
func (tccb *TalentCollectionCreateBulk) Save(ctx context.Context) ([]*TalentCollection, error) {
	specs := make([]*sqlgraph.CreateSpec, len(tccb.builders))
	nodes := make([]*TalentCollection, len(tccb.builders))
	mutators := make([]Mutator, len(tccb.builders))
	for i := range tccb.builders {
		func(i int, root context.Context) {
			builder := tccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TalentCollectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, tccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, tccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, tccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (tccb *TalentCollectionCreateBulk) SaveX(ctx context.Context) []*TalentCollection {
	v, err := tccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (tccb *TalentCollectionCreateBulk) Exec(ctx context.Context) error {
	_, err := tccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tccb *TalentCollectionCreateBulk) ExecX(ctx context.Context) {
	if err := tccb.Exec(ctx); err != nil {
		panic(err)
	}
}
