// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/10hourlabs/tentn/ent/education"
	"github.com/10hourlabs/tentn/ent/emergencycontact"
	"github.com/10hourlabs/tentn/ent/jobapplication"
	"github.com/10hourlabs/tentn/ent/mission"
	"github.com/10hourlabs/tentn/ent/portfoliolink"
	"github.com/10hourlabs/tentn/ent/predicate"
	"github.com/10hourlabs/tentn/ent/skill"
	"github.com/10hourlabs/tentn/ent/talent"
	"github.com/10hourlabs/tentn/ent/user"
	"github.com/10hourlabs/tentn/ent/workexperience"
)

// TalentQuery is the builder for querying Talent entities.
type TalentQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.Talent
	// eager-loading edges.
	withUser              *UserQuery
	withReferrer          *TalentQuery
	withReferees          *TalentQuery
	withPortfoliolinks    *PortfolioLinkQuery
	withSkills            *SkillQuery
	withJobApplications   *JobApplicationQuery
	withWorkExperiences   *WorkExperienceQuery
	withEducations        *EducationQuery
	withEmergencyContacts *EmergencyContactQuery
	withMissions          *MissionQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the TalentQuery builder.
func (tq *TalentQuery) Where(ps ...predicate.Talent) *TalentQuery {
	tq.predicates = append(tq.predicates, ps...)
	return tq
}

// Limit adds a limit step to the query.
func (tq *TalentQuery) Limit(limit int) *TalentQuery {
	tq.limit = &limit
	return tq
}

// Offset adds an offset step to the query.
func (tq *TalentQuery) Offset(offset int) *TalentQuery {
	tq.offset = &offset
	return tq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (tq *TalentQuery) Unique(unique bool) *TalentQuery {
	tq.unique = &unique
	return tq
}

// Order adds an order step to the query.
func (tq *TalentQuery) Order(o ...OrderFunc) *TalentQuery {
	tq.order = append(tq.order, o...)
	return tq
}

// QueryUser chains the current query on the "user" edge.
func (tq *TalentQuery) QueryUser() *UserQuery {
	query := &UserQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, talent.UserTable, talent.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReferrer chains the current query on the "referrer" edge.
func (tq *TalentQuery) QueryReferrer() *TalentQuery {
	query := &TalentQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(talent.Table, talent.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, talent.ReferrerTable, talent.ReferrerColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReferees chains the current query on the "referees" edge.
func (tq *TalentQuery) QueryReferees() *TalentQuery {
	query := &TalentQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(talent.Table, talent.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.RefereesTable, talent.RefereesColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPortfoliolinks chains the current query on the "portfoliolinks" edge.
func (tq *TalentQuery) QueryPortfoliolinks() *PortfolioLinkQuery {
	query := &PortfolioLinkQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(portfoliolink.Table, portfoliolink.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.PortfoliolinksTable, talent.PortfoliolinksColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QuerySkills chains the current query on the "skills" edge.
func (tq *TalentQuery) QuerySkills() *SkillQuery {
	query := &SkillQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(skill.Table, skill.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.SkillsTable, talent.SkillsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryJobApplications chains the current query on the "job_applications" edge.
func (tq *TalentQuery) QueryJobApplications() *JobApplicationQuery {
	query := &JobApplicationQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(jobapplication.Table, jobapplication.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.JobApplicationsTable, talent.JobApplicationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryWorkExperiences chains the current query on the "work_experiences" edge.
func (tq *TalentQuery) QueryWorkExperiences() *WorkExperienceQuery {
	query := &WorkExperienceQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(workexperience.Table, workexperience.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.WorkExperiencesTable, talent.WorkExperiencesColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEducations chains the current query on the "educations" edge.
func (tq *TalentQuery) QueryEducations() *EducationQuery {
	query := &EducationQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(education.Table, education.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.EducationsTable, talent.EducationsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEmergencyContacts chains the current query on the "emergency_contacts" edge.
func (tq *TalentQuery) QueryEmergencyContacts() *EmergencyContactQuery {
	query := &EmergencyContactQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(emergencycontact.Table, emergencycontact.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.EmergencyContactsTable, talent.EmergencyContactsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMissions chains the current query on the "missions" edge.
func (tq *TalentQuery) QueryMissions() *MissionQuery {
	query := &MissionQuery{config: tq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := tq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(talent.Table, talent.FieldID, selector),
			sqlgraph.To(mission.Table, mission.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, talent.MissionsTable, talent.MissionsColumn),
		)
		fromU = sqlgraph.SetNeighbors(tq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Talent entity from the query.
// Returns a *NotFoundError when no Talent was found.
func (tq *TalentQuery) First(ctx context.Context) (*Talent, error) {
	nodes, err := tq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{talent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (tq *TalentQuery) FirstX(ctx context.Context) *Talent {
	node, err := tq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Talent ID from the query.
// Returns a *NotFoundError when no Talent ID was found.
func (tq *TalentQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{talent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (tq *TalentQuery) FirstIDX(ctx context.Context) int {
	id, err := tq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Talent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Talent entity is found.
// Returns a *NotFoundError when no Talent entities are found.
func (tq *TalentQuery) Only(ctx context.Context) (*Talent, error) {
	nodes, err := tq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{talent.Label}
	default:
		return nil, &NotSingularError{talent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (tq *TalentQuery) OnlyX(ctx context.Context) *Talent {
	node, err := tq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Talent ID in the query.
// Returns a *NotSingularError when more than one Talent ID is found.
// Returns a *NotFoundError when no entities are found.
func (tq *TalentQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = tq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = &NotSingularError{talent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (tq *TalentQuery) OnlyIDX(ctx context.Context) int {
	id, err := tq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Talents.
func (tq *TalentQuery) All(ctx context.Context) ([]*Talent, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return tq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (tq *TalentQuery) AllX(ctx context.Context) []*Talent {
	nodes, err := tq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Talent IDs.
func (tq *TalentQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := tq.Select(talent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (tq *TalentQuery) IDsX(ctx context.Context) []int {
	ids, err := tq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (tq *TalentQuery) Count(ctx context.Context) (int, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return tq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (tq *TalentQuery) CountX(ctx context.Context) int {
	count, err := tq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (tq *TalentQuery) Exist(ctx context.Context) (bool, error) {
	if err := tq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return tq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (tq *TalentQuery) ExistX(ctx context.Context) bool {
	exist, err := tq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the TalentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (tq *TalentQuery) Clone() *TalentQuery {
	if tq == nil {
		return nil
	}
	return &TalentQuery{
		config:                tq.config,
		limit:                 tq.limit,
		offset:                tq.offset,
		order:                 append([]OrderFunc{}, tq.order...),
		predicates:            append([]predicate.Talent{}, tq.predicates...),
		withUser:              tq.withUser.Clone(),
		withReferrer:          tq.withReferrer.Clone(),
		withReferees:          tq.withReferees.Clone(),
		withPortfoliolinks:    tq.withPortfoliolinks.Clone(),
		withSkills:            tq.withSkills.Clone(),
		withJobApplications:   tq.withJobApplications.Clone(),
		withWorkExperiences:   tq.withWorkExperiences.Clone(),
		withEducations:        tq.withEducations.Clone(),
		withEmergencyContacts: tq.withEmergencyContacts.Clone(),
		withMissions:          tq.withMissions.Clone(),
		// clone intermediate query.
		sql:    tq.sql.Clone(),
		path:   tq.path,
		unique: tq.unique,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithUser(opts ...func(*UserQuery)) *TalentQuery {
	query := &UserQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withUser = query
	return tq
}

// WithReferrer tells the query-builder to eager-load the nodes that are connected to
// the "referrer" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithReferrer(opts ...func(*TalentQuery)) *TalentQuery {
	query := &TalentQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withReferrer = query
	return tq
}

// WithReferees tells the query-builder to eager-load the nodes that are connected to
// the "referees" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithReferees(opts ...func(*TalentQuery)) *TalentQuery {
	query := &TalentQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withReferees = query
	return tq
}

// WithPortfoliolinks tells the query-builder to eager-load the nodes that are connected to
// the "portfoliolinks" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithPortfoliolinks(opts ...func(*PortfolioLinkQuery)) *TalentQuery {
	query := &PortfolioLinkQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withPortfoliolinks = query
	return tq
}

// WithSkills tells the query-builder to eager-load the nodes that are connected to
// the "skills" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithSkills(opts ...func(*SkillQuery)) *TalentQuery {
	query := &SkillQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withSkills = query
	return tq
}

// WithJobApplications tells the query-builder to eager-load the nodes that are connected to
// the "job_applications" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithJobApplications(opts ...func(*JobApplicationQuery)) *TalentQuery {
	query := &JobApplicationQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withJobApplications = query
	return tq
}

// WithWorkExperiences tells the query-builder to eager-load the nodes that are connected to
// the "work_experiences" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithWorkExperiences(opts ...func(*WorkExperienceQuery)) *TalentQuery {
	query := &WorkExperienceQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withWorkExperiences = query
	return tq
}

// WithEducations tells the query-builder to eager-load the nodes that are connected to
// the "educations" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithEducations(opts ...func(*EducationQuery)) *TalentQuery {
	query := &EducationQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withEducations = query
	return tq
}

// WithEmergencyContacts tells the query-builder to eager-load the nodes that are connected to
// the "emergency_contacts" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithEmergencyContacts(opts ...func(*EmergencyContactQuery)) *TalentQuery {
	query := &EmergencyContactQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withEmergencyContacts = query
	return tq
}

// WithMissions tells the query-builder to eager-load the nodes that are connected to
// the "missions" edge. The optional arguments are used to configure the query builder of the edge.
func (tq *TalentQuery) WithMissions(opts ...func(*MissionQuery)) *TalentQuery {
	query := &MissionQuery{config: tq.config}
	for _, opt := range opts {
		opt(query)
	}
	tq.withMissions = query
	return tq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Talent.Query().
//		GroupBy(talent.FieldUUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (tq *TalentQuery) GroupBy(field string, fields ...string) *TalentGroupBy {
	group := &TalentGroupBy{config: tq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := tq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return tq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UUID uuid.UUID `json:"uuid,omitempty"`
//	}
//
//	client.Talent.Query().
//		Select(talent.FieldUUID).
//		Scan(ctx, &v)
//
func (tq *TalentQuery) Select(fields ...string) *TalentSelect {
	tq.fields = append(tq.fields, fields...)
	return &TalentSelect{TalentQuery: tq}
}

func (tq *TalentQuery) prepareQuery(ctx context.Context) error {
	for _, f := range tq.fields {
		if !talent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if tq.path != nil {
		prev, err := tq.path(ctx)
		if err != nil {
			return err
		}
		tq.sql = prev
	}
	return nil
}

func (tq *TalentQuery) sqlAll(ctx context.Context) ([]*Talent, error) {
	var (
		nodes       = []*Talent{}
		_spec       = tq.querySpec()
		loadedTypes = [10]bool{
			tq.withUser != nil,
			tq.withReferrer != nil,
			tq.withReferees != nil,
			tq.withPortfoliolinks != nil,
			tq.withSkills != nil,
			tq.withJobApplications != nil,
			tq.withWorkExperiences != nil,
			tq.withEducations != nil,
			tq.withEmergencyContacts != nil,
			tq.withMissions != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &Talent{config: tq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, tq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := tq.withUser; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*Talent)
		for i := range nodes {
			fk := nodes[i].UserID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(user.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.User = n
			}
		}
	}

	if query := tq.withReferrer; query != nil {
		ids := make([]int, 0, len(nodes))
		nodeids := make(map[int][]*Talent)
		for i := range nodes {
			fk := nodes[i].ReferrerID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(talent.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "referrer_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Referrer = n
			}
		}
	}

	if query := tq.withReferees; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Referees = []*Talent{}
		}
		query.Where(predicate.Talent(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.RefereesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.ReferrerID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "referrer_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Referees = append(node.Edges.Referees, n)
		}
	}

	if query := tq.withPortfoliolinks; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Portfoliolinks = []*PortfolioLink{}
		}
		query.Where(predicate.PortfolioLink(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.PortfoliolinksColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TalentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Portfoliolinks = append(node.Edges.Portfoliolinks, n)
		}
	}

	if query := tq.withSkills; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Skills = []*Skill{}
		}
		query.Where(predicate.Skill(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.SkillsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TalentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Skills = append(node.Edges.Skills, n)
		}
	}

	if query := tq.withJobApplications; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.JobApplications = []*JobApplication{}
		}
		query.Where(predicate.JobApplication(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.JobApplicationsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TalentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.JobApplications = append(node.Edges.JobApplications, n)
		}
	}

	if query := tq.withWorkExperiences; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.WorkExperiences = []*WorkExperience{}
		}
		query.Where(predicate.WorkExperience(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.WorkExperiencesColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TalentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.WorkExperiences = append(node.Edges.WorkExperiences, n)
		}
	}

	if query := tq.withEducations; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Educations = []*Education{}
		}
		query.Where(predicate.Education(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.EducationsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TalentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Educations = append(node.Edges.Educations, n)
		}
	}

	if query := tq.withEmergencyContacts; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.EmergencyContacts = []*EmergencyContact{}
		}
		query.Where(predicate.EmergencyContact(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.EmergencyContactsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TalentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.EmergencyContacts = append(node.Edges.EmergencyContacts, n)
		}
	}

	if query := tq.withMissions; query != nil {
		fks := make([]driver.Value, 0, len(nodes))
		nodeids := make(map[int]*Talent)
		for i := range nodes {
			fks = append(fks, nodes[i].ID)
			nodeids[nodes[i].ID] = nodes[i]
			nodes[i].Edges.Missions = []*Mission{}
		}
		query.Where(predicate.Mission(func(s *sql.Selector) {
			s.Where(sql.InValues(talent.MissionsColumn, fks...))
		}))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			fk := n.TalentID
			node, ok := nodeids[fk]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "talent_id" returned %v for node %v`, fk, n.ID)
			}
			node.Edges.Missions = append(node.Edges.Missions, n)
		}
	}

	return nodes, nil
}

func (tq *TalentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := tq.querySpec()
	_spec.Node.Columns = tq.fields
	if len(tq.fields) > 0 {
		_spec.Unique = tq.unique != nil && *tq.unique
	}
	return sqlgraph.CountNodes(ctx, tq.driver, _spec)
}

func (tq *TalentQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := tq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (tq *TalentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   talent.Table,
			Columns: talent.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: talent.FieldID,
			},
		},
		From:   tq.sql,
		Unique: true,
	}
	if unique := tq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := tq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, talent.FieldID)
		for i := range fields {
			if fields[i] != talent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := tq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := tq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := tq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := tq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (tq *TalentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(tq.driver.Dialect())
	t1 := builder.Table(talent.Table)
	columns := tq.fields
	if len(columns) == 0 {
		columns = talent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if tq.sql != nil {
		selector = tq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if tq.unique != nil && *tq.unique {
		selector.Distinct()
	}
	for _, p := range tq.predicates {
		p(selector)
	}
	for _, p := range tq.order {
		p(selector)
	}
	if offset := tq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := tq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// TalentGroupBy is the group-by builder for Talent entities.
type TalentGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (tgb *TalentGroupBy) Aggregate(fns ...AggregateFunc) *TalentGroupBy {
	tgb.fns = append(tgb.fns, fns...)
	return tgb
}

// Scan applies the group-by query and scans the result into the given value.
func (tgb *TalentGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := tgb.path(ctx)
	if err != nil {
		return err
	}
	tgb.sql = query
	return tgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (tgb *TalentGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := tgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(tgb.fields) > 1 {
		return nil, errors.New("ent: TalentGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := tgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (tgb *TalentGroupBy) StringsX(ctx context.Context) []string {
	v, err := tgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = tgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (tgb *TalentGroupBy) StringX(ctx context.Context) string {
	v, err := tgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(tgb.fields) > 1 {
		return nil, errors.New("ent: TalentGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := tgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (tgb *TalentGroupBy) IntsX(ctx context.Context) []int {
	v, err := tgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = tgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (tgb *TalentGroupBy) IntX(ctx context.Context) int {
	v, err := tgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(tgb.fields) > 1 {
		return nil, errors.New("ent: TalentGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := tgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (tgb *TalentGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := tgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = tgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (tgb *TalentGroupBy) Float64X(ctx context.Context) float64 {
	v, err := tgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(tgb.fields) > 1 {
		return nil, errors.New("ent: TalentGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := tgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (tgb *TalentGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := tgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (tgb *TalentGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = tgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (tgb *TalentGroupBy) BoolX(ctx context.Context) bool {
	v, err := tgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (tgb *TalentGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range tgb.fields {
		if !talent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := tgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := tgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (tgb *TalentGroupBy) sqlQuery() *sql.Selector {
	selector := tgb.sql.Select()
	aggregation := make([]string, 0, len(tgb.fns))
	for _, fn := range tgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(tgb.fields)+len(tgb.fns))
		for _, f := range tgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(tgb.fields...)...)
}

// TalentSelect is the builder for selecting fields of Talent entities.
type TalentSelect struct {
	*TalentQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ts *TalentSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ts.prepareQuery(ctx); err != nil {
		return err
	}
	ts.sql = ts.TalentQuery.sqlQuery(ctx)
	return ts.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ts *TalentSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ts.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ts.fields) > 1 {
		return nil, errors.New("ent: TalentSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ts *TalentSelect) StringsX(ctx context.Context) []string {
	v, err := ts.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ts.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ts *TalentSelect) StringX(ctx context.Context) string {
	v, err := ts.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ts.fields) > 1 {
		return nil, errors.New("ent: TalentSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ts *TalentSelect) IntsX(ctx context.Context) []int {
	v, err := ts.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ts.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ts *TalentSelect) IntX(ctx context.Context) int {
	v, err := ts.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ts.fields) > 1 {
		return nil, errors.New("ent: TalentSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ts *TalentSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ts.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ts.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ts *TalentSelect) Float64X(ctx context.Context) float64 {
	v, err := ts.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ts.fields) > 1 {
		return nil, errors.New("ent: TalentSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ts.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ts *TalentSelect) BoolsX(ctx context.Context) []bool {
	v, err := ts.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ts *TalentSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ts.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{talent.Label}
	default:
		err = fmt.Errorf("ent: TalentSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ts *TalentSelect) BoolX(ctx context.Context) bool {
	v, err := ts.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ts *TalentSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ts.sql.Query()
	if err := ts.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
