// Code generated by entc, DO NOT EDIT.

package jobpayment

import (
	"time"

	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the jobpayment type in the database.
	Label = "job_payment"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldJobID holds the string denoting the job_id field in the database.
	FieldJobID = "job_id"
	// FieldAmount holds the string denoting the amount field in the database.
	FieldAmount = "amount"
	// FieldPaidTo holds the string denoting the paid_to field in the database.
	FieldPaidTo = "paid_to"
	// FieldRefID holds the string denoting the ref_id field in the database.
	FieldRefID = "ref_id"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldCurrency holds the string denoting the currency field in the database.
	FieldCurrency = "currency"
	// FieldPaymentLink holds the string denoting the payment_link field in the database.
	FieldPaymentLink = "payment_link"
	// FieldPayload holds the string denoting the payload field in the database.
	FieldPayload = "payload"
	// EdgeJob holds the string denoting the job edge name in mutations.
	EdgeJob = "job"
	// Table holds the table name of the jobpayment in the database.
	Table = "job_payments"
	// JobTable is the table that holds the job relation/edge.
	JobTable = "job_payments"
	// JobInverseTable is the table name for the Job entity.
	// It exists in this package in order to avoid circular dependency with the "job" package.
	JobInverseTable = "jobs"
	// JobColumn is the table column denoting the job relation/edge.
	JobColumn = "job_id"
)

// Columns holds all SQL columns for jobpayment fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldJobID,
	FieldAmount,
	FieldPaidTo,
	FieldRefID,
	FieldMessage,
	FieldCurrency,
	FieldPaymentLink,
	FieldPayload,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultAmount holds the default value on creation for the "amount" field.
	DefaultAmount float64
	// DefaultRefID holds the default value on creation for the "ref_id" field.
	DefaultRefID string
	// DefaultCurrency holds the default value on creation for the "currency" field.
	DefaultCurrency string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)
