// Code generated by entc, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"github.com/10hourlabs/tentn/ent/schema/userrole"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldFirstName holds the string denoting the first_name field in the database.
	FieldFirstName = "first_name"
	// FieldLastName holds the string denoting the last_name field in the database.
	FieldLastName = "last_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldApproved holds the string denoting the approved field in the database.
	FieldApproved = "approved"
	// FieldPhotoURL holds the string denoting the photo_url field in the database.
	FieldPhotoURL = "photo_url"
	// EdgeOauth2Clients holds the string denoting the oauth2_clients edge name in mutations.
	EdgeOauth2Clients = "oauth2_clients"
	// EdgeOauth2Tokens holds the string denoting the oauth2_tokens edge name in mutations.
	EdgeOauth2Tokens = "oauth2_tokens"
	// EdgeTalents holds the string denoting the talents edge name in mutations.
	EdgeTalents = "talents"
	// EdgeSlackAppInstalls holds the string denoting the slack_app_installs edge name in mutations.
	EdgeSlackAppInstalls = "slack_app_installs"
	// EdgeJobs holds the string denoting the jobs edge name in mutations.
	EdgeJobs = "jobs"
	// EdgeEmailTemplates holds the string denoting the email_templates edge name in mutations.
	EdgeEmailTemplates = "email_templates"
	// EdgeTalentCollections holds the string denoting the talent_collections edge name in mutations.
	EdgeTalentCollections = "talent_collections"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeFileUploads holds the string denoting the file_uploads edge name in mutations.
	EdgeFileUploads = "file_uploads"
	// Table holds the table name of the user in the database.
	Table = "users"
	// Oauth2ClientsTable is the table that holds the oauth2_clients relation/edge.
	Oauth2ClientsTable = "oauth2clients"
	// Oauth2ClientsInverseTable is the table name for the Oauth2Client entity.
	// It exists in this package in order to avoid circular dependency with the "oauth2client" package.
	Oauth2ClientsInverseTable = "oauth2clients"
	// Oauth2ClientsColumn is the table column denoting the oauth2_clients relation/edge.
	Oauth2ClientsColumn = "user_id"
	// Oauth2TokensTable is the table that holds the oauth2_tokens relation/edge.
	Oauth2TokensTable = "oauth2tokens"
	// Oauth2TokensInverseTable is the table name for the Oauth2Token entity.
	// It exists in this package in order to avoid circular dependency with the "oauth2token" package.
	Oauth2TokensInverseTable = "oauth2tokens"
	// Oauth2TokensColumn is the table column denoting the oauth2_tokens relation/edge.
	Oauth2TokensColumn = "user_id"
	// TalentsTable is the table that holds the talents relation/edge.
	TalentsTable = "talents"
	// TalentsInverseTable is the table name for the Talent entity.
	// It exists in this package in order to avoid circular dependency with the "talent" package.
	TalentsInverseTable = "talents"
	// TalentsColumn is the table column denoting the talents relation/edge.
	TalentsColumn = "user_id"
	// SlackAppInstallsTable is the table that holds the slack_app_installs relation/edge.
	SlackAppInstallsTable = "slack_app_installs"
	// SlackAppInstallsInverseTable is the table name for the SlackAppInstall entity.
	// It exists in this package in order to avoid circular dependency with the "slackappinstall" package.
	SlackAppInstallsInverseTable = "slack_app_installs"
	// SlackAppInstallsColumn is the table column denoting the slack_app_installs relation/edge.
	SlackAppInstallsColumn = "user_id"
	// JobsTable is the table that holds the jobs relation/edge.
	JobsTable = "jobs"
	// JobsInverseTable is the table name for the Job entity.
	// It exists in this package in order to avoid circular dependency with the "job" package.
	JobsInverseTable = "jobs"
	// JobsColumn is the table column denoting the jobs relation/edge.
	JobsColumn = "user_id"
	// EmailTemplatesTable is the table that holds the email_templates relation/edge.
	EmailTemplatesTable = "email_templates"
	// EmailTemplatesInverseTable is the table name for the EmailTemplate entity.
	// It exists in this package in order to avoid circular dependency with the "emailtemplate" package.
	EmailTemplatesInverseTable = "email_templates"
	// EmailTemplatesColumn is the table column denoting the email_templates relation/edge.
	EmailTemplatesColumn = "user_id"
	// TalentCollectionsTable is the table that holds the talent_collections relation/edge.
	TalentCollectionsTable = "talent_collections"
	// TalentCollectionsInverseTable is the table name for the TalentCollection entity.
	// It exists in this package in order to avoid circular dependency with the "talentcollection" package.
	TalentCollectionsInverseTable = "talent_collections"
	// TalentCollectionsColumn is the table column denoting the talent_collections relation/edge.
	TalentCollectionsColumn = "user_id"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "user_id"
	// FileUploadsTable is the table that holds the file_uploads relation/edge.
	FileUploadsTable = "file_uploads"
	// FileUploadsInverseTable is the table name for the FileUpload entity.
	// It exists in this package in order to avoid circular dependency with the "fileupload" package.
	FileUploadsInverseTable = "file_uploads"
	// FileUploadsColumn is the table column denoting the file_uploads relation/edge.
	FileUploadsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldFirstName,
	FieldLastName,
	FieldEmail,
	FieldRole,
	FieldApproved,
	FieldPhotoURL,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultApproved holds the default value on creation for the "approved" field.
	DefaultApproved bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r userrole.Role) error {
	switch r {
	case "talent", "recruiter", "developer":
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for role field: %q", r)
	}
}
